In [1]:
import pandas as pd

df = pd.read_csv("synthetic_dubai_data/Dubai_Real_Estate_Synthetic_Messy.csv")

df.head()

,Transaction_ID,Transaction_Date,Area,Property_Type,Property_Sub_Type,Property_Size_SqM,Transaction_Amount_AED,Rooms,Parking_Spaces,Transaction_Type,Source_Channel
0,DXB-101018,2025-09-21,Jumeirah Village Circle,Apartment,2 BR,407.9,4480815.0,2.0,3,Sale,Developer
1,DXB-100222,2023-06-23,Jumeirah,Villa,6 BR,71.7,2034323.0,6.0,3,Sale,Broker
2,DXB-100310,2026-07-08,Al Barsha,Apartment,Studio,126.7,2012324.0,0.0,0,Sale,Developer
3,DXB-101268,2023-07-24,Dubai Marina,Apartment,1 BR,36.8,1064931.0,1.0,2,Mortgage,DLD
4,DXB-101361,2025-12-05,Jumeirah,APARTMENT,2 BR,114.6,"AED 2,170,758",2.0,3,Sale,Developer

In [2]:
df.shape

(1525, 11)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1525 entries, 0 to 1524
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Transaction_ID          1525 non-null   str
 1   Transaction_Date        1525 non-null   str
 2   Area                    1488 non-null   str
 3   Property_Type           1525 non-null   str
 4   Property_Sub_Type       1525 non-null   str
 5   Property_Size_SqM       1493 non-null   float64
 6   Transaction_Amount_AED  1503 non-null   str
 7   Rooms                   1488 non-null   float64
 8   Parking_Spaces          1525 non-null   int64
 9   Transaction_Type        1525 non-null   str
 10  Source_Channel          1525 non-null   str
dtypes: float64(2), int64(1), str(8)
memory usage: 227.6 KB

In [4]:
print(df.isna().sum())

Transaction_ID             0
Transaction_Date           0
Area                      37
Property_Type              0
Property_Sub_Type          0
Property_Size_SqM         32
Transaction_Amount_AED    22
Rooms                     37
Parking_Spaces             0
Transaction_Type           0
Source_Channel             0
dtype: int64

In [5]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 23

In [6]:
print("Duplicate Transaction IDs:", df["Transaction_ID"].duplicated().sum())

Duplicate Transaction IDs: 25

In [7]:
print(df.to_string())

     Transaction_ID Transaction_Date                      Area    Property_Type Property_Sub_Type  Property_Size_SqM Transaction_Amount_AED  Rooms  Parking_Spaces Transaction_Type Source_Channel
0        DXB-101018       2025-09-21   Jumeirah Village Circle        Apartment              2 BR              407.9              4480815.0    2.0               3             Sale      Developer
1        DXB-100222       2023-06-23                  Jumeirah            Villa              6 BR               71.7              2034323.0    6.0               3             Sale         Broker
2        DXB-100310       2026-07-08                 Al Barsha        Apartment            Studio              126.7              2012324.0    0.0               0             Sale      Developer
3        DXB-101268       2023-07-24              Dubai Marina        Apartment              1 BR               36.8              1064931.0    1.0               2         Mortgage            DLD
4        DXB-101361       2025-12-05                  Jumeirah        APARTMENT              2 BR              114.6          AED 2,170,758    2.0               3             Sale      Developer
5        DXB-100307       2024-08-03   Jumeirah Village Circle            Villa              6 BR              202.9              3054340.0    6.0               2             Sale      Developer
6        DXB-100292       2024-01-05              Business Bay  Hotel Apartment              2 BR               79.4          AED 2,276,293    2.0               2             Sale         Broker
7        DXB-101103       2025-02-19              Dubai Marina        Townhouse              3 BR              368.5              6759447.0    3.0               3             Sale         Broker
8        DXB-100491       2024-05-21        International City            Villa              5 BR              516.9              3802875.0    5.0               0             Sale         Broker
9        DXB-100509       2024-08-07        Dubai Hills Estate        Apartment              1 BR              113.9              2584807.0    1.0               3         Mortgage      Developer
10       DXB-101463      26-Jun-2026        International City        Apartment              1 BR              114.0              1291138.0    1.0               1             Sale      Developer
11       DXB-100684       2023-06-10                    Mirdif            Villa              6 BR               74.8              1059119.0    6.0               1             Sale      Developer
12       DXB-101248       2026-05-09                 Bur Dubai        Penthouse              4 BR              114.8              2795820.0    4.0               2        Mortgage             DLD
13       DXB-100485       2024-10-16              Dubai Marina        Apartment            Studio             8000.0               85000000    0.0               1             Sale            DLD
14       DXB-101315       2025-12-01      Jumeirah Lake Towers            villa              3 BR               77.9              1381612.0    3.0               3             Sale      Developer
15       DXB-100042       2023-03-15                       JLT            Villa              6 BR              131.0              3212161.0    6.0               0         Mortgage            DLD
16       DXB-100818       2025-09-11        International City            Villa              6 BR               77.7              1200052.0    6.0               2             Sale            DLD
17       DXB-100781       2023-12-01              Business Bay  Hotel Apartment              2 BR               71.5              1813218.0    2.0               2             Sale            DLD
18       DXB-101293       14/07/2024            Downtown Dubai        Apartment              3 BR              136.8              2184626.0    3.0               1             Sale      Developer
19       DXB-100618       09-09-2023             Palm Jumeirah        Apartment              3 BR               57.3              1925315.0    3.0               1         Mortgage            DLD
20       DXB-100662       2023-05-30                    Mirdif        Apartment              1 BR              433.1              5258295.0    1.0               3             Sale            DLD
21       DXB-101132       2025-03-06           Arabian Ranches        Apartment              2 BR              138.2              3365064.0    2.0               0             Sale            DLD
22       DXB-100211       2024-12-07                       NaN            Villa              6 BR               88.3              1898903.0    6.0               2         Mortgage            DLD
23       DXB-100602       2025-06-19   Jumeirah Village Circle  Hotel Apartment            Studio               52.7            AED 505,183    0.0               3             Sale            DLD
24       DXB-101190       2023-11-25             Palm Jumeirah        Apartment              1 BR              133.8              2507350.0    1.0               2         Mortgage            DLD
25       DXB-100835       2023-08-03           Arabian Ranches            Villa              3 BR              183.1              5390353.0    3.0               3             Sale            DLD
26       DXB-101403       03/01/2025                    Mirdif        Apartment              3 BR              119.5          AED 1,907,395    3.0               3             Sale      Developer
27       DXB-101426       2023-11-20              Business Bay       Apartment               2 BR              322.2              8862546.0    2.0               0             Sale            DLD
28       DXB-100400       2025-06-06                     Deira        apartment              1 BR               88.4               824425.0    1.0               1         Mortgage            DLD
29       DXB-100581       2024-08-02                  Jumeirah       Apartment               2 BR             8000.0               85000000    2.0               1             Sale            DLD
30       DXB-100203       2024-04-25   Jumeirah Village Circle        Apartment              3 BR              220.6            AED 663,064    3.0               3             Sale      Developer
31       DXB-100838       2023-04-30                    Mirdif        Apartment              1 BR               52.5                    NaN    1.0               2             Sale            DLD
32       DXB-100512       2023-12-26            Downtown Dubai        Apartment              2 BR               91.8              3770999.0    2.0               1             Sale         Broker
33       DXB-100534       2024-03-22            Downtown Dubai        Apartment            Studio               38.8               782327.0    0.0               1             Sale      Developer
34       DXB-100935       2024-11-24                     Deira        Apartment              3 BR              130.7              1531225.0    NaN               0             Sale            DLD
35       DXB-100871       2023-07-18            Downtown Dubai        Apartment              2 BR              188.8              7258832.0    2.0               3             Sale            DLD
36       DXB-100997       2024-08-02                     Deira        Apartment              1 BR               61.5               448373.0    1.0               2             Sale         Broker
37       DXB-100716       2024-11-28        Dubai Hills Estate            Villa              6 BR              113.1              2130218.0    NaN               0             Sale            DLD
38       DXB-100819       2026-04-04                 Bur Dubai        Apartment            Studio               99.7              1741876.0    0.0               3             Sale         Broker
39       DXB-101017       2024-10-03   Jumeirah village circle        Townhouse              4 BR               73.7              1032251.0    4.0               1             Sale            DLD
40       DXB-100365       2024-10-07                  Jumeirah        Apartment              2 BR               86.2              1929240.0    2.0               0             Sale      Developer
41       DXB-101379       2025-05-10                 Bur Dubai              APT            Studio              112.6              1575446.0    0.0               2             Sale         Broker
42       DXB-100234       2024-12-18       Dubai Silicon Oasis  Hotel Apartment              2 BR               78.2          AED 1,312,158    2.0               1             Sale            DLD
43       DXB-100938       2023-04-05           Arabian Ranches        Penthouse              3 BR               62.5              1962426.0    3.0               2             Sale      Developer
44       DXB-100560       2024-04-12            Downtown Dubai              APT              2 BR              125.6              2910886.0    2.0               3             Sale            DLD
45       DXB-101416       2025-02-12                 Al Barsha        apartment              1 BR              146.3              2348310.0    1.0               1             Sale      Developer
46       DXB-100889       2026-07-21                     Deira            Villa              6 BR              106.2              1194972.0    6.0               3             Sale            DLD
47       DXB-100273       2024-05-26             Palm Jumeirah            VILLA              6 BR              143.1              5894671.0    6.0               2             Sale            DLD
48       DXB-101493       2024-10-17              Business Bay        Townhouse              3 BR              120.8              2557790.0    3.0               0             Sale      Developer
49       DXB-101337       2023-05-08      Jumeirah Lake Towers            Villa              3 BR               54.6              1543872.0    3.0               3             Sale            DLD
50       DXB-101383       2024-09-29       Dubai Silicon Oasis  Hotel Apartment            Studio              154.0              2302379.0    0.0               2             Sale            DLD
51       DXB-100576       18/06/2026        International City  Hotel Apartment            Studio               62.2            AED 715,260    0.0               3             Sale            DLD
52       DXB-100086       2024-09-13   Jumeirah Village Circle            villa              3 BR               35.7               325844.0    3.0               2             Sale         Broker
53       DXB-101200       2024-04-01           Arabian Ranches            Villa              5 BR              105.7              3241288.0    5.0               2             Sale         Broker
54       DXB-100874       2023-10-04        International City            Villa              5 BR              120.0              1259910.0    5.0               0         Mortgage            DLD
55       DXB-100653       2023-01-04                 Al Barsha        Apartment              2 BR               62.6               766716.0    2.0               3             Sale      Developer
56       DXB-100846       2023-11-10                  Jumeirah        apartment              1 BR               39.0              1468142.0    1.0               3             Sale            DLD
57       DXB-101300       2024-03-04      Jumeirah Lake Towers        apartment            Studio              238.5              4555410.0    0.0               0         Mortgage            DLD
58       DXB-100852       2023-12-21           Downtown Dubai         Penthouse              2 BR               56.3              2321643.0    2.0               1         Mortgage         Broker
59       DXB-100057       2024-07-29   Jumeirah Village Circle            Villa              6 BR              156.4              3636052.0    6.0               0             Sale            DLD
60       DXB-100074       2023-09-27       Dubai Silicon Oasis        Apartment              2 BR              197.0              1909703.0    2.0               0         Mortgage            DLD
61       DXB-100156       2026-02-03                  Jumeirah        Apartment            Studio              187.4              4181274.0    0.0               0            Sale             DLD
62       DXB-100389       2024-09-09           Arabian Ranches        Penthouse              3 BR              120.4              4800864.0    3.0               3         Mortgage            DLD
63       DXB-101444       2023-06-03                  Jumeirah        APARTMENT              1 BR              102.2              2158832.0    1.0               1             Sale      Developer
64       DXB-101339       2023-05-12                 Al Barsha        Apartment              2 BR              136.6              2182853.0    2.0               2             Sale      Developer
65       DXB-100338       2024-11-06                     Deira        Apartment              3 BR               91.9               362830.0    3.0               0         Mortgage      Developer
66       DXB-100403       2025-05-28                    Mirdif        Apartment              2 BR               96.0               617503.0    2.0               1             Sale         Broker
67       DXB-101334       2025-10-18                 Bur Dubai  Hotel Apartment            Studio              132.7              2478664.0    0.0               0             Sale            DLD
68       DXB-100786       2025-11-14   Jumeirah village circle        TOWNHOUSE              2 BR              128.3               -1000000    2.0               0             Sale            DLD
69       DXB-101296       2024-03-09             Palm Jumeirah        Apartment              3 BR              180.9              3904328.0    3.0               1             Sale            DLD
70       DXB-101238       2023-02-03                  Jumeirah        apartment            Studio              153.5              4241623.0    0.0               2         Mortgage         Broker
71       DXB-100495       2023-05-28                 Al Barsha        Apartment            Studio              308.7          AED 6,870,925    0.0               2             Sale         Broker
72       DXB-101131       2025-12-31                 Bur Dubai        Apartment              2 BR              121.5              1199694.0    2.0               0             Sale            DLD
73       DXB-101072       2024-07-22                     Deira              APT            Studio               92.8               829145.0    0.0               2             Sale            DLD
74       DXB-100500       2026-02-11             Dubai Marina         Townhouse              2 BR              116.6              3124009.0    2.0               3             Sale            DLD
75       DXB-101283       2026-01-30             Palm Jumeirah            Villa              6 BR              213.8              7950433.0    6.0               0             Sale         Broker
76       DXB-101068       2024-10-30                  Jumeirah        Apartment              1 BR              179.9              2011320.0    1.0               2             Sale            DLD
77       DXB-101398       2024-12-08            Downtown Dubai            Villa              5 BR               57.1              1927614.0    5.0               0             Sale            DLD
78       DXB-100678       05-31-2026       Dubai Silicon Oasis        Apartment            Studio               72.2               880747.0    0.0               0             Sale            DLD
79       DXB-101359       2023-04-20                    Mirdif        Apartment              2 BR               68.3               787240.0    2.0               2         Mortgage      Developer
80       DXB-100478       2023-01-14             Palm Jumeirah            Villa              6 BR               36.1              1513378.0    6.0               0         Mortgage            DLD
81       DXB-100191       2024-07-22           Arabian Ranches        Apartment            Studio              125.6              3960584.0    0.0               3             Sale     Developer
82       DXB-100559       2024-10-31                 Al Barsha              APT              2 BR               94.2              1310916.0    2.0               0             Sale            DLD
83       DXB-101347       2025-07-15   Jumeirah Village Circle        Apartment              2 BR              238.6              3116857.0    2.0               0             Sale            DLD
84       DXB-100774       2025-07-30             Palm Jumeirah        apartment              2 BR              152.7              3709960.0    2.0               3         Mortgage            DLD
85       DXB-100350       2023-09-04   Jumeirah Village Circle            Villa              6 BR              225.3              3922494.0    6.0               0             Sale            DLD
86       DXB-100253       2025-01-18        Dubai Hills Estate        Apartment              3 BR               64.1              1057963.0    3.0               0             Sale            DLD
87       DXB-101125       2025-11-29                 Al Barsha            Villa              5 BR              152.0              2421725.0    5.0               0             Sale         Broker
88       DXB-100669       2023-01-25              Business Bay        Apartment            Studio               51.2              1336022.0    0.0               2             Sale         Broker
89       DXB-100372       2025-05-31      Jumeirah Lake Towers        Apartment            Studio              146.0              1843007.0    0.0               2             Sale            DLD
90       DXB-100993       2025-05-13      Jumeirah Lake Towers        Apartment            Studio              169.8              2659975.0    0.0               1         Mortgage            DLD
91       DXB-100655       2024-12-03                 Al Barsha        Apartment              3 BR               70.8               735133.0    3.0               2             Sale            DLD
92       DXB-101162       2025-11-17       Dubai Silicon Oasis        Townhouse              4 BR               41.7               612891.0    4.0               2         Mortgage            DLD
93       DXB-101013       2025-09-30                 Al Barsha  Hotel Apartment              2 BR              225.7              2367063.0    2.0               1             Sale            DLD
94       DXB-101272       2026-03-28                 Bur Dubai        Apartment              1 BR               95.4              1233926.0    1.0               2         Mortgage            DLD
95       DXB-100923       2025-02-25             Palm Jumeirah        Apartment            Studio               58.4               976354.0    0.0               0             Sale            DLD
96       DXB-101212       2024-10-22             Palm Jumeirah           Villa               4 BR               39.9               747843.0    NaN               2             Sale            DLD
97       DXB-100390       2023-04-02              Business Bay            Villa              6 BR              168.7          AED 3,427,761    6.0               2             Sale            DLD
98       DXB-101367       2023-11-22   Jumeirah Village Circle        Apartment              3 BR               86.2              1068041.0    3.0               2         Mortgage            DLD
99       DXB-100717       2025-03-13              Business Bay              APT              2 BR              241.3              7026878.0    2.0               0             Sale            DLD
100      DXB-100921       2023-06-14        International City       town house              4 BR              115.6              1200211.0    4.0               3         Mortgage            DLD

In [8]:
off_df = pd.read_csv("official/Dubai_Real_Estate_Clean_English.csv")

off_df.head()

,Quarter,Type,الربع السنوي,Description,الوصف,Year,Value,Title,العنوان,Quarter_Number,النوع,sort_id
0,First Quarter,Units,First Quarter,Value,قيمة,2026,85008984976,Sales,المبايعات,1,وحده,1
1,First Quarter,Units,First Quarter,Number,عدد,2026,38524,Sales,المبايعات,1,وحده,2
2,First Quarter,Building,First Quarter,Value,قيمة,2026,3597832936,Sales,المبايعات,1,مبنى,3
3,First Quarter,Building,First Quarter,Number,عدد,2026,117,Sales,المبايعات,1,مبنى,4
4,First Quarter,Land,First Quarter,Value,قيمة,2026,61282752869,Sales,المبايعات,1,أرض,5

In [9]:
off_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 744 entries, 0 to 743
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Quarter         744 non-null    str
 1   Type            744 non-null    str
 2   الربع السنوي    744 non-null    str
 3   Description     744 non-null    str
 4   الوصف           744 non-null    str
 5   Year            744 non-null    int64
 6   Value           744 non-null    int64
 7   Title           744 non-null    str
 8   العنوان         744 non-null    str
 9   Quarter_Number  744 non-null    int64
 10  النوع           744 non-null    str
 11  sort_id         744 non-null    int64
dtypes: int64(4), str(8)
memory usage: 121.8 KB

In [10]:
print("Duplicate rows:", off_df.duplicated().sum())

Duplicate rows: 0

In [11]:
off_df.columns.tolist()

['Quarter',
 'Type',
 'الربع السنوي',
 'Description',
 'الوصف',
 'Year',
 'Value',
 'Title',
 'العنوان',
 'Quarter_Number',
 'النوع',
 'sort_id']

In [12]:
off_df["Type"].unique()

<ArrowStringArray>
['Units', 'Building', 'Land', 'Villa']
Length: 4, dtype: str

In [13]:
off_df["Type"].value_counts()

Type
Units       216
Building    216
Land        216
Villa        96
Name: count, dtype: int64

In [14]:
off_df["Year"].value_counts().sort_index()

Year
2016    72
2017    72
2018    72
2019    72
2020    72
2021    96
2022    96
2023    96
2025    72
2026    24
Name: count, dtype: int64

In [15]:
off_df["Description"].value_counts()

Description
Value     372
Number    372
Name: count, dtype: int64

In [16]:
off_df.groupby(["Type", "Description"]).size()

Type      Description
Building  Number         108
          Value          108
Land      Number         108
          Value          108
Units     Number         108
          Value          108
Villa     Number          48
          Value           48
dtype: int64

In [17]:
off_df.groupby(["Type", "Description"]).size()

Type      Description
Building  Number         108
          Value          108
Land      Number         108
          Value          108
Units     Number         108
          Value          108
Villa     Number          48
          Value           48
dtype: int64

In [18]:
off_df["Title"].value_counts()

Title
Sales        248
Mortgages    248
Other        248
Name: count, dtype: int64

In [19]:
off_df["Quarter"].value_counts().sort_index()

Quarter
First Quarter     210
Fourth Quarter    186
Second Quarter    186
Third Quarter     162
Name: count, dtype: int64

In [20]:
off_df[["Quarter", "Quarter_Number"]].drop_duplicates().sort_values("Quarter_Number")

            Quarter  Quarter_Number
0     First Quarter               1
48   Second Quarter               2
144   Third Quarter               3
72   Fourth Quarter               4

In [21]:
off_df[["Title", "Type", "Description", "Value"]].head(20)

        Title      Type Description        Value
0       Sales     Units       Value  85008984976
1       Sales     Units      Number        38524
2       Sales  Building       Value   3597832936
3       Sales  Building      Number          117
4       Sales      Land       Value  61282752869
5       Sales      Land      Number         3798
6       Sales     Villa       Value  26478955434
7       Sales     Villa      Number         5548
8   Mortgages     Units       Value  10471845517
9   Mortgages     Units      Number         6067
10  Mortgages  Building       Value  13338055646
11  Mortgages  Building      Number          125
12  Mortgages      Land       Value  26810360867
13  Mortgages      Land      Number         1769
14  Mortgages     Villa       Value   9274922994
15  Mortgages     Villa      Number         2229
16      Other     Units       Value   5952273315
17      Other     Units      Number         1594
18      Other  Building       Value   2346395984
19      Other  Building      Number           38

In [22]:
off_df[["Year", "Quarter", "Quarter_Number"]].drop_duplicates().sort_values(["Year", "Quarter_Number"])

     Year         Quarter  Quarter_Number
672  2016   First Quarter               1
690  2016  Second Quarter               2
708  2016   Third Quarter               3
726  2016  Fourth Quarter               4
600  2017   First Quarter               1
618  2017  Second Quarter               2
636  2017   Third Quarter               3
654  2017  Fourth Quarter               4
528  2018   First Quarter               1
546  2018  Second Quarter               2
564  2018   Third Quarter               3
582  2018  Fourth Quarter               4
456  2019   First Quarter               1
474  2019  Second Quarter               2
492  2019   Third Quarter               3
510  2019  Fourth Quarter               4
384  2020   First Quarter               1
402  2020  Second Quarter               2
420  2020   Third Quarter               3
438  2020  Fourth Quarter               4
288  2021   First Quarter               1
312  2021  Second Quarter               2
336  2021   Third Quarter               3
360  2021  Fourth Quarter               4
192  2022   First Quarter               1
216  2022  Second Quarter               2
240  2022   Third Quarter               3
264  2022  Fourth Quarter               4
96   2023   First Quarter               1
120  2023  Second Quarter               2
144  2023   Third Quarter               3
168  2023  Fourth Quarter               4
24   2025   First Quarter               1
48   2025  Second Quarter               2
72   2025  Fourth Quarter               4
0    2026   First Quarter               1

In [23]:
off_df[off_df["Description"] == "Value"]["Value"].describe()

count    3.720000e+02
mean     9.691012e+09
std      1.460417e+10
min      2.671991e+07
25%      1.325233e+09
50%      4.148308e+09
75%      1.086321e+10
max      9.743897e+10
Name: Value, dtype: float64

In [24]:
off_df[off_df["Description"] == "Value"].groupby("Title")["Value"].sum()

Title
Mortgages    1393770206477
Other         259850576556
Sales        1951435736760
Name: Value, dtype: int64

In [25]:
off_df[off_df["Description"] == "Value"].groupby("Title")["Value"].sum().div(
    off_df[off_df["Description"] == "Value"]["Value"].sum()
).mul(100)

Title
Mortgages    38.661536
Other         7.207947
Sales        54.130517
Name: Value, dtype: float64

In [26]:
off_df[off_df["Description"] == "Value"].groupby(["Year", "Title"])["Value"].sum()

Year  Title
2016  Mortgages    138483660723
      Other         27344477914
      Sales        102882182957
2017  Mortgages    137355267128
      Other         32902461815
      Sales        114264781281
2018  Mortgages    119900262052
      Other         28967637452
      Sales         74645006712
2019  Mortgages    127325532406
      Other         19208439048
      Sales         81030047833
2020  Mortgages     87550682971
      Other         14955863989
      Sales         72257078384
2021  Mortgages    128239094858
      Other         20619897006
      Sales        150973932992
2022  Mortgages    273625122261
      Other         29856680583
      Sales        266726283573
2023  Mortgages    190454930555
      Other         32366742100
      Sales        399949383919
2025  Mortgages    130940468499
      Other         38159751209
      Sales        512338512894
2026  Mortgages     59895185024
      Other         15468625440
      Sales        176368526215
Name: Value, dtype: int64

In [27]:
off_df[off_df["Description"] == "Value"].pivot_table(
    index="Year",
    columns="Title",
    values="Value",
    aggfunc="sum"
)

Title     Mortgages        Other         Sales
Year
2016   138483660723  27344477914  102882182957
2017   137355267128  32902461815  114264781281
2018   119900262052  28967637452   74645006712
2019   127325532406  19208439048   81030047833
2020    87550682971  14955863989   72257078384
2021   128239094858  20619897006  150973932992
2022   273625122261  29856680583  266726283573
2023   190454930555  32366742100  399949383919
2025   130940468499  38159751209  512338512894
2026    59895185024  15468625440  176368526215

In [28]:
sales_by_year = off_df[off_df["Description"] == "Value"].groupby("Year")["Value"].sum()

sales_by_year.pct_change() * 100

Year
2016          NaN
2017     5.884474
2018   -21.442804
2019     1.812474
2020   -23.202435
2021    71.564835
2022    90.175274
2023     9.218208
2025     9.420424
2026   -63.058699
Name: Value, dtype: float64

In [29]:
sales_share = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Year", "Title"])["Value"]
    .sum()
)

sales_share

Year  Title
2016  Mortgages    138483660723
      Other         27344477914
      Sales        102882182957
2017  Mortgages    137355267128
      Other         32902461815
      Sales        114264781281
2018  Mortgages    119900262052
      Other         28967637452
      Sales         74645006712
2019  Mortgages    127325532406
      Other         19208439048
      Sales         81030047833
2020  Mortgages     87550682971
      Other         14955863989
      Sales         72257078384
2021  Mortgages    128239094858
      Other         20619897006
      Sales        150973932992
2022  Mortgages    273625122261
      Other         29856680583
      Sales        266726283573
2023  Mortgages    190454930555
      Other         32366742100
      Sales        399949383919
2025  Mortgages    130940468499
      Other         38159751209
      Sales        512338512894
2026  Mortgages     59895185024
      Other         15468625440
      Sales        176368526215
Name: Value, dtype: int64

In [30]:
off_df[off_df["Description"] == "Number"].groupby(["Year", "Title"])["Value"].sum()

Year  Title
2016  Mortgages     14530
      Other          4250
      Sales         41561
2017  Mortgages     15666
      Other          4099
      Sales         49279
2018  Mortgages     14183
      Other          5111
      Sales         34259
2019  Mortgages     12547
      Other          3766
      Sales         40265
2020  Mortgages     12937
      Other          3030
      Sales         35315
2021  Mortgages     20081
      Other          3671
      Sales         61169
2022  Mortgages     20479
      Other          4712
      Sales         97705
2023  Mortgages     25891
      Other          7475
      Sales        127612
2025  Mortgages     31596
      Other          7111
      Sales        158353
2026  Mortgages     10190
      Other          2063
      Sales         47987
Name: Value, dtype: int64

In [31]:
value_df = off_df[off_df["Description"] == "Value"].groupby(["Year", "Title"])["Value"].sum()

number_df = off_df[off_df["Description"] == "Number"].groupby(["Year", "Title"])["Value"].sum()

average_value = value_df / number_df

average_value

Year  Title
2016  Mortgages    9.530878e+06
      Other        6.433995e+06
      Sales        2.475450e+06
2017  Mortgages    8.767731e+06
      Other        8.026948e+06
      Sales        2.318732e+06
2018  Mortgages    8.453801e+06
      Other        5.667704e+06
      Sales        2.178844e+06
2019  Mortgages    1.014789e+07
      Other        5.100488e+06
      Sales        2.012419e+06
2020  Mortgages    6.767464e+06
      Other        4.935929e+06
      Sales        2.046073e+06
2021  Mortgages    6.386091e+06
      Other        5.616970e+06
      Sales        2.468145e+06
2022  Mortgages    1.336125e+07
      Other        6.336307e+06
      Sales        2.729914e+06
2023  Mortgages    7.356028e+06
      Other        4.329999e+06
      Sales        3.134105e+06
2025  Mortgages    4.144210e+06
      Other        5.366299e+06
      Sales        3.235420e+06
2026  Mortgages    5.877840e+06
      Other        7.498122e+06
      Sales        3.675340e+06
Name: Value, dtype: float64

In [32]:
average_sales = average_value.xs("Sales", level="Title")

average_sales

Year
2016    2.475450e+06
2017    2.318732e+06
2018    2.178844e+06
2019    2.012419e+06
2020    2.046073e+06
2021    2.468145e+06
2022    2.729914e+06
2023    3.134105e+06
2025    3.235420e+06
2026    3.675340e+06
Name: Value, dtype: float64

In [33]:
average_sales = average_value.xs("Sales", level="Title")
average_sales

Year
2016    2.475450e+06
2017    2.318732e+06
2018    2.178844e+06
2019    2.012419e+06
2020    2.046073e+06
2021    2.468145e+06
2022    2.729914e+06
2023    3.134105e+06
2025    3.235420e+06
2026    3.675340e+06
Name: Value, dtype: float64

In [34]:
average_sales.pct_change() * 100

Year
2016          NaN
2017    -6.330905
2018    -6.032954
2019    -7.638216
2020     1.672334
2021    20.628354
2022    10.605936
2023    14.805975
2025     3.232677
2026    13.596978
Name: Value, dtype: float64

In [35]:
number_sales = off_df[off_df["Description"] == "Number"].groupby("Year")["Value"].sum()

number_sales

Year
2016     60341
2017     69044
2018     53553
2019     56578
2020     51282
2021     84921
2022    122896
2023    160978
2025    197060
2026     60240
Name: Value, dtype: int64

In [36]:
number_sales.pct_change() * 100

Year
2016          NaN
2017    14.423029
2018   -22.436417
2019     5.648610
2020    -9.360529
2021    65.596116
2022    44.718032
2023    30.987176
2025    22.414243
2026   -69.430630
Name: Value, dtype: float64

In [37]:
total_sales = off_df[off_df["Description"] == "Value"].groupby("Year")["Value"].sum()

total_sales

Year
2016    268710321594
2017    284522510224
2018    223512906216
2019    227564019287
2020    174763625344
2021    299832924856
2022    570208086417
2023    622771056574
2025    681438732602
2026    251732336679
Name: Value, dtype: int64

In [38]:
total_sales.pct_change() * 100

Year
2016          NaN
2017     5.884474
2018   -21.442804
2019     1.812474
2020   -23.202435
2021    71.564835
2022    90.175274
2023     9.218208
2025     9.420424
2026   -63.058699
Name: Value, dtype: float64

In [39]:
quarter_sales = off_df[off_df["Description"] == "Value"].groupby(
    "Quarter"
)["Value"].sum()

quarter_sales

Quarter
First Quarter     1058813474885
Fourth Quarter    1074498821069
Second Quarter     837280227029
Third Quarter      634463996810
Name: Value, dtype: int64

In [40]:
quarter_sales_by_year = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Year", "Quarter"])["Value"]
    .sum()
)

quarter_sales_by_year

Year  Quarter
2016  First Quarter      55975993830
      Fourth Quarter     87328336575
      Second Quarter     71477034863
      Third Quarter      53928956326
2017  First Quarter      81274795777
      Fourth Quarter     79646979248
      Second Quarter     56629202885
      Third Quarter      66971532314
2018  First Quarter      57949007736
      Fourth Quarter     61082202632
      Second Quarter     53377978756
      Third Quarter      51103717092
2019  First Quarter      56440756432
      Fourth Quarter     67768016422
      Second Quarter     60698471284
      Third Quarter      42656775149
2020  First Quarter      47551878149
      Fourth Quarter     43226130116
      Second Quarter     24291566588
      Third Quarter      59694050491
2021  First Quarter      69471480341
      Fourth Quarter     79129905693
      Second Quarter     74475198739
      Third Quarter      76756340083
2022  First Quarter      88074696423
      Fourth Quarter    213964573953
      Second Quarter    131949357547
      Third Quarter     136219458494
2023  First Quarter     156979373559
      Fourth Quarter    192574305348
      Second Quarter    126084210806
      Third Quarter     147133166861
2025  First Quarter     193363155959
      Fourth Quarter    249778371082
      Second Quarter    238297205561
2026  First Quarter     251732336679
Name: Value, dtype: int64

In [41]:
quarter_sales_by_year = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Year", "Quarter", "Quarter_Number"])["Value"]
    .sum()
    .sort_index(level=["Year", "Quarter_Number"])
)

quarter_sales_by_year

Year  Quarter         Quarter_Number
2016  First Quarter   1                  55975993830
      Second Quarter  2                  71477034863
      Third Quarter   3                  53928956326
      Fourth Quarter  4                  87328336575
2017  First Quarter   1                  81274795777
      Second Quarter  2                  56629202885
      Third Quarter   3                  66971532314
      Fourth Quarter  4                  79646979248
2018  First Quarter   1                  57949007736
      Second Quarter  2                  53377978756
      Third Quarter   3                  51103717092
      Fourth Quarter  4                  61082202632
2019  First Quarter   1                  56440756432
      Second Quarter  2                  60698471284
      Third Quarter   3                  42656775149
      Fourth Quarter  4                  67768016422
2020  First Quarter   1                  47551878149
      Second Quarter  2                  24291566588
      Third Quarter   3                  59694050491
      Fourth Quarter  4                  43226130116
2021  First Quarter   1                  69471480341
      Second Quarter  2                  74475198739
      Third Quarter   3                  76756340083
      Fourth Quarter  4                  79129905693
2022  First Quarter   1                  88074696423
      Second Quarter  2                 131949357547
      Third Quarter   3                 136219458494
      Fourth Quarter  4                 213964573953
2023  First Quarter   1                 156979373559
      Second Quarter  2                 126084210806
      Third Quarter   3                 147133166861
      Fourth Quarter  4                 192574305348
2025  First Quarter   1                 193363155959
      Second Quarter  2                 238297205561
      Fourth Quarter  4                 249778371082
2026  First Quarter   1                 251732336679
Name: Value, dtype: int64

In [42]:
best_quarter_by_year = quarter_sales_by_year.groupby(level="Year").idxmax()

best_quarter_by_year

Year
2016    (2016, Fourth Quarter, 4)
2017     (2017, First Quarter, 1)
2018    (2018, Fourth Quarter, 4)
2019    (2019, Fourth Quarter, 4)
2020     (2020, Third Quarter, 3)
2021    (2021, Fourth Quarter, 4)
2022    (2022, Fourth Quarter, 4)
2023    (2023, Fourth Quarter, 4)
2025    (2025, Fourth Quarter, 4)
2026     (2026, First Quarter, 1)
Name: Value, dtype: object

In [43]:
best_quarter_by_year = best_quarter_by_year.apply(lambda x: x[1])

best_quarter_by_year

Year
2016    Fourth Quarter
2017     First Quarter
2018    Fourth Quarter
2019    Fourth Quarter
2020     Third Quarter
2021    Fourth Quarter
2022    Fourth Quarter
2023    Fourth Quarter
2025    Fourth Quarter
2026     First Quarter
Name: Value, dtype: str

In [44]:
quarter_sales_growth = quarter_sales_by_year.pct_change() * 100

quarter_sales_growth

Year  Quarter         Quarter_Number
2016  First Quarter   1                        NaN
      Second Quarter  2                  27.692302
      Third Quarter   3                 -24.550653
      Fourth Quarter  4                  61.932184
2017  First Quarter   1                  -6.931932
      Second Quarter  2                 -30.323783
      Third Quarter   3                  18.263244
      Fourth Quarter  4                  18.926619
2018  First Quarter   1                 -27.242680
      Second Quarter  2                  -7.888019
      Third Quarter   3                  -4.260674
      Fourth Quarter  4                  19.525949
2019  First Quarter   1                  -7.598688
      Second Quarter  2                   7.543688
      Third Quarter   3                 -29.723477
      Fourth Quarter  4                  58.868119
2020  First Quarter   1                 -29.831386
      Second Quarter  2                 -48.915653
      Third Quarter   3                 145.739814
      Fourth Quarter  4                 -27.587205
2021  First Quarter   1                  60.716400
      Second Quarter  2                   7.202550
      Third Quarter   3                   3.062954
      Fourth Quarter  4                   3.092338
2022  First Quarter   1                  11.303932
      Second Quarter  2                  49.815285
      Third Quarter   3                   3.236167
      Fourth Quarter  4                  57.073429
2023  First Quarter   1                 -26.633007
      Second Quarter  2                 -19.681033
      Third Quarter   3                  16.694363
      Fourth Quarter  4                  30.884361
2025  First Quarter   1                   0.409634
      Second Quarter  2                  23.238165
      Fourth Quarter  4                   4.818003
2026  First Quarter   1                   0.782280
Name: Value, dtype: float64

In [45]:
quarter_sales_growth.idxmax(), quarter_sales_growth.max()

((np.int64(2020), 'Third Quarter', np.int64(3)),
 np.float64(145.73981375284694))

In [46]:
quarter_sales_growth.idxmin(), quarter_sales_growth.min()

((np.int64(2020), 'Second Quarter', np.int64(2)),
 np.float64(-48.915652685926894))

In [47]:
transaction_type_value = (
    off_df[off_df["Description"] == "Value"]
    .groupby("Title")["Value"]
    .sum()
    .sort_values(ascending=False)
)

transaction_type_value

Title
Sales        1951435736760
Mortgages    1393770206477
Other         259850576556
Name: Value, dtype: int64

In [48]:
transaction_type_share = (
    transaction_type_value / transaction_type_value.sum() * 100
).round(2)

transaction_type_share

Title
Sales        54.13
Mortgages    38.66
Other         7.21
Name: Value, dtype: float64

In [49]:
transaction_type_by_year = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Year", "Title"])["Value"]
    .sum()
)

transaction_type_by_year

Year  Title
2016  Mortgages    138483660723
      Other         27344477914
      Sales        102882182957
2017  Mortgages    137355267128
      Other         32902461815
      Sales        114264781281
2018  Mortgages    119900262052
      Other         28967637452
      Sales         74645006712
2019  Mortgages    127325532406
      Other         19208439048
      Sales         81030047833
2020  Mortgages     87550682971
      Other         14955863989
      Sales         72257078384
2021  Mortgages    128239094858
      Other         20619897006
      Sales        150973932992
2022  Mortgages    273625122261
      Other         29856680583
      Sales        266726283573
2023  Mortgages    190454930555
      Other         32366742100
      Sales        399949383919
2025  Mortgages    130940468499
      Other         38159751209
      Sales        512338512894
2026  Mortgages     59895185024
      Other         15468625440
      Sales        176368526215
Name: Value, dtype: int64

In [50]:
average_transaction_value = (
    total_sales / number_sales
).round(2)

average_transaction_value

Year
2016    4453196.36
2017    4120886.83
2018    4173676.66
2019    4022129.08
2020    3407894.10
2021    3530727.67
2022    4639761.15
2023    3868671.85
2025    3458026.65
2026    4178823.65
Name: Value, dtype: float64

In [51]:
driver_analysis = pd.concat(
    [
        number_sales.pct_change() * 100,
        average_transaction_value.pct_change() * 100,
        total_sales.pct_change() * 100
    ],
    axis=1
)

driver_analysis.columns = [
    "Transaction_Count_Growth_%",
    "Average_Value_Growth_%",
    "Total_Value_Growth_%"
]

driver_analysis.round(2)

      Transaction_Count_Growth_%  Average_Value_Growth_%  Total_Value_Growth_%
Year
2016                         NaN                     NaN                   NaN
2017                       14.42                   -7.46                  5.88
2018                      -22.44                    1.28                -21.44
2019                        5.65                   -3.63                  1.81
2020                       -9.36                  -15.27                -23.20
2021                       65.60                    3.60                 71.56
2022                       44.72                   31.41                 90.18
2023                       30.99                  -16.62                  9.22
2025                       22.41                  -10.61                  9.42
2026                      -69.43                   20.84                -63.06

In [52]:
year_coverage = (
    off_df.groupby("Year")["Quarter_Number"]
    .nunique()
)

year_coverage

Year
2016    4
2017    4
2018    4
2019    4
2020    4
2021    4
2022    4
2023    4
2025    3
2026    1
Name: Quarter_Number, dtype: int64

In [53]:
transaction_mix_by_year = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Year", "Title"])["Value"]
    .sum()
    .unstack()
)

transaction_mix_by_year

Title     Mortgages        Other         Sales
Year
2016   138483660723  27344477914  102882182957
2017   137355267128  32902461815  114264781281
2018   119900262052  28967637452   74645006712
2019   127325532406  19208439048   81030047833
2020    87550682971  14955863989   72257078384
2021   128239094858  20619897006  150973932992
2022   273625122261  29856680583  266726283573
2023   190454930555  32366742100  399949383919
2025   130940468499  38159751209  512338512894
2026    59895185024  15468625440  176368526215

In [54]:
transaction_type_by_quarter = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Quarter_Number", "Quarter", "Title"])["Value"]
    .sum()
    .unstack("Title")
)

transaction_type_by_quarter

Title                             Mortgages        Other         Sales
Quarter_Number Quarter
1              First Quarter   373097437414  76960101647  608755935824
2              Second Quarter  307914784607  54780827666  474584614756
3              Third Quarter   274766157260  45693992234  314003847316
4              Fourth Quarter  437991827196  82415655009  554091338864

In [55]:
off_df["Type"].unique()

<ArrowStringArray>
['Units', 'Building', 'Land', 'Villa']
Length: 4, dtype: str

In [56]:
property_type_value = (
    off_df[off_df["Description"] == "Value"]
    .groupby("Type")["Value"]
    .sum()
    .sort_values(ascending=False)
)

property_type_value

Type
Land        1816480499758
Units       1127896179781
Villa        365924001319
Building     294755838935
Name: Value, dtype: int64

In [57]:
property_type_transaction = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Type", "Title"])["Value"]
    .sum()
    .unstack("Title")
)

property_type_transaction

Title        Mortgages         Other         Sales
Type
Building  165799558976   42097421360   86858858599
Land      985335953918  141282870470  689861675370
Units     145938818371   53139008577  928818352833
Villa      96695875212   23331276149  245896849958

In [58]:
property_type_transaction_share = (
    property_type_transaction
    .div(property_type_transaction.sum(axis=1), axis=0)
    * 100
).round(2)

property_type_transaction_share

Title     Mortgages  Other  Sales
Type
Building      56.25  14.28  29.47
Land          54.24   7.78  37.98
Units         12.94   4.71  82.35
Villa         26.43   6.38  67.20

In [59]:
property_type_by_year = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Year", "Type"])["Value"]
    .sum()
    .unstack()
)

property_type_by_year

Type      Building          Land         Units         Villa
Year
2016  1.135935e+10  2.025048e+11  5.484621e+10           NaN
2017  1.512720e+10  2.049562e+11  6.443907e+10           NaN
2018  1.088217e+10  1.654469e+11  4.718382e+10           NaN
2019  1.366325e+10  1.509251e+11  6.297567e+10           NaN
2020  1.080649e+10  1.231491e+11  4.080808e+10           NaN
2021  5.745043e+10  9.682767e+10  8.419385e+10  6.136097e+10
2022  5.531521e+10  2.841107e+11  1.620455e+11  6.873666e+10
2023  5.350345e+10  2.535649e+11  2.223995e+11  9.330324e+10
2025  4.736601e+10  2.418501e+11  2.875714e+11  1.046513e+11
2026  1.928228e+10  9.314507e+10  1.014331e+11  3.787188e+10

In [60]:
property_type_share_by_year = (
    property_type_by_year
    .div(property_type_by_year.sum(axis=1), axis=0)
    * 100
).round(2)

property_type_share_by_year

Type  Building   Land  Units  Villa
Year
2016      4.23  75.36  20.41    NaN
2017      5.32  72.04  22.65    NaN
2018      4.87  74.02  21.11    NaN
2019      6.00  66.32  27.67    NaN
2020      6.18  70.47  23.35    NaN
2021     19.16  32.29  28.08  20.47
2022      9.70  49.83  28.42  12.05
2023      8.59  40.72  35.71  14.98
2025      6.95  35.49  42.20  15.36
2026      7.66  37.00  40.29  15.04

In [61]:
property_type_by_quarter = (
    off_df[off_df["Description"] == "Value"]
    .groupby(["Quarter_Number", "Quarter", "Type"])["Value"]
    .sum()
    .unstack("Type")
)

property_type_share_by_quarter = (
    property_type_by_quarter
    .div(property_type_by_quarter.sum(axis=1), axis=0)
    * 100
).round(2)

property_type_share_by_quarter

Type                           Building   Land  Units  Villa
Quarter_Number Quarter
1              First Quarter       8.65  47.25  32.51  11.60
2              Second Quarter      8.11  49.31  32.09  10.49
3              Third Quarter       8.05  54.24  28.31   9.40
4              Fourth Quarter      7.83  52.04  31.21   8.91

In [62]:
property_type_share_change = (
    property_type_share_by_year
    .diff()
    .round(2)
)

property_type_share_change

Type  Building   Land  Units  Villa
Year
2016       NaN    NaN    NaN    NaN
2017      1.09  -3.32   2.24    NaN
2018     -0.45   1.98  -1.54    NaN
2019      1.13  -7.70   6.56    NaN
2020      0.18   4.15  -4.32    NaN
2021     12.98 -38.18   4.73    NaN
2022     -9.46  17.54   0.34  -8.42
2023     -1.11  -9.11   7.29   2.93
2025     -1.64  -5.23   6.49   0.38
2026      0.71   1.51  -1.91  -0.32

In [63]:
# Change in transaction-type market composition by year

transaction_mix_share_by_year = (
    transaction_mix_by_year
    .div(transaction_mix_by_year.sum(axis=1), axis=0)
    * 100
).round(2)

transaction_mix_share_change = (
    transaction_mix_share_by_year
    .diff()
    .round(2)
)

transaction_mix_share_change

Title  Mortgages  Other  Sales
Year
2016         NaN    NaN    NaN
2017       -3.26   1.38   1.87
2018        5.36   1.40  -6.76
2019        2.31  -4.52   2.21
2020       -5.85   0.12   5.74
2021       -7.33  -1.68   9.00
2022        5.22  -1.64  -3.57
2023      -17.41  -0.04  17.44
2025      -11.36   0.40  10.96
2026        4.57   0.54  -5.12

In [64]:
transaction_mix_volatility = (
    transaction_mix_share_by_year
    .std()
    .round(2)
    .sort_values(ascending=False)
)

transaction_mix_volatility

Title
Sales        15.05
Mortgages    13.09
Other         2.76
dtype: float64

In [65]:
duplicate_transaction_ids = df["Transaction_ID"].duplicated().sum()

duplicate_transaction_ids

np.int64(25)

In [66]:
duplicate_id_rows = (
    df[df["Transaction_ID"].duplicated(keep=False)]
    .sort_values("Transaction_ID")
)

duplicate_id_rows

,Transaction_ID,Transaction_Date,Area,Property_Type,Property_Sub_Type,Property_Size_SqM,Transaction_Amount_AED,Rooms,Parking_Spaces,Transaction_Type,Source_Channel
815,DXB-100051,2023-09-22,Jumeirah Village Circle,Apartment,Studio,53.2,757963.0,0.0,1,Mortgage,DLD
933,DXB-100051,2023-09-22,Jumeirah Village Circle,Apartment,Studio,53.2,757963.0,0.0,1,Mortgage,DLD
346,DXB-100070,2024-11-22,Palm Jumeirah,Apartment,2 BR,46.9,1822311.0,2.0,3,Sale,DLD
530,DXB-100070,2024-11-22,Palm Jumeirah,Apartment,2 BR,46.9,1822311.0,2.0,3,Sale,DLD
447,DXB-100259,2025-06-25,Palm Jumeirah,villa,5 BR,NaN,4581034.0,5.0,1,Sale,Broker
859,DXB-100259,2025-06-25,Palm Jumeirah,villa,5 BR,NaN,4581034.0,5.0,1,Sale,Broker
1344,DXB-100413,2024-06-05,Downtown Dubai,Penthouse,3 BR,126.6,5844099.0,3.0,0,Mortgage,Developer
1353,DXB-100413,2024-06-05,Downtown Dubai,Penthouse,3 BR,126.6,5844099.0,3.0,0,Mortgage,Developer
631,DXB-100422,2023-10-10,International City,Apartment,2 BR,25.0,"AED 322,477",2.0,3,Sale,Developer
1461,DXB-100422,2023-10-10,International City,Apartment,2 BR,25.0,"AED 322,477",2.0,3,Sale,Developer
820,DXB-100433,2026-04-30,Dubai Hills Estate,Townhouse,4 BR,111.8,2211146.0,4.0,0,Sale,DLD
988,DXB-100433,2026-04-30,Dubai Hills Estate,Townhouse,4 BR,111.8,2211146.0,4.0,0,Sale,DLD
108,DXB-100451,2024-10-30,Dubai Marina,Penthouse,2 BR,105.6,3561526.0,2.0,0,Mortgage,DLD
810,DXB-100451,2024-10-30,Dubai Marina,Penthouse,2 BR,105.6,3561526.0,2.0,0,Mortgage,DLD
459,DXB-100607,2024-09-11,Arabian Ranches,Apartment,3 BR,121.2,2621540.0,3.0,1,Sale,DLD
1124,DXB-100607,2024-09-11,Arabian Ranches,Apartment,3 BR,121.2,2621540.0,3.0,1,Sale,DLD
692,DXB-100712,2024-02-28,Deira,Townhouse,3 BR,48.8,616398.0,3.0,1,Sale,DLD
987,DXB-100712,2024-02-28,Deira,Townhouse,3 BR,48.8,616398.0,3.0,1,Sale,DLD
705,DXB-100741,2025-07-13,JLT,Apartment,3 BR,52.0,1488884.0,3.0,0,Mortgage,DLD
1496,DXB-100741,2025-07-13,JLT,Apartment,3 BR,52.0,1488884.0,3.0,0,Mortgage,DLD
434,DXB-100861,2026-06-16,International City,Townhouse,4 BR,NaN,520265.0,4.0,1,Mortgage,DLD
882,DXB-100861,2026-06-16,International City,Townhouse,4 BR,NaN,520265.0,4.0,1,Mortgage,DLD
290,DXB-100888,2023-03-29,Jumeirah Village Circle,Apartment,1 BR,216.5,1879585.0,1.0,1,Sale,DLD
976,DXB-100888,2023-03-29,Jumeirah Village Circle,Apartment,1 BR,216.5,1879585.0,1.0,1,Sale,DLD
1391,DXB-101063,2023-10-24,Al Barsha,Villa,3 BR,191.8,3036627.0,3.0,0,Sale,DLD
1481,DXB-101063,2023-10-24,Al Barsha,Villa,3 BR,191.8,3036627.0,3.0,0,Sale,DLD
904,DXB-101116,2023-10-27,Dubai Marina,Apartment,3 BR,113.7,1915422.0,3.0,2,Sale,DLD
910,DXB-101116,2023-10-27,Dubai Marina,Apartment,3 BR,113.7,1915422.0,3.0,2,Sale,DLD
501,DXB-101128,2025-05-22,Dubai Silicon Oasis,Villa,4 BR,197.3,4770509.0,4.0,3,Sale,Broker
1022,DXB-101128,2025-05-22,Dubai Silicon Oasis,Villa,4 BR,197.3,4770509.0,4.0,3,Sale,Broker
24,DXB-101190,2023-11-25,Palm Jumeirah,Apartment,1 BR,133.8,2507350.0,1.0,2,Mortgage,DLD
469,DXB-101190,2023-11-25,Palm Jumeirah,Apartment,1 BR,133.8,2507350.0,1.0,2,Mortgage,DLD
876,DXB-101199,2023-07-03,Business Bay,town house,3 BR,133.3,889496.0,3.0,0,Sale,DLD
1293,DXB-101199,2023-07-03,Business Bay,town house,3 BR,133.3,889496.0,3.0,0,Sale,DLD
339,DXB-101249,2023-11-10,Dubai Hills Estate,Hotel Apartment,Studio,50.4,1197129.0,0.0,0,Mortgage,DLD
496,DXB-101249,2023-11-10,Dubai Hills Estate,Hotel Apartment,Studio,50.4,1197129.0,0.0,0,Mortgage,DLD
3,DXB-101268,2023-07-24,Dubai Marina,Apartment,1 BR,36.8,1064931.0,1.0,2,Mortgage,DLD
1085,DXB-101268,2023-07-24,Dubai Marina,Apartment,1 BR,36.8,1064931.0,1.0,2,Mortgage,DLD
94,DXB-101272,2026-03-28,Bur Dubai,Apartment,1 BR,95.4,1233926.0,1.0,2,Mortgage,DLD
1352,DXB-101272,2026-03-28,Bur Dubai,Apartment,1 BR,95.4,1233926.0,1.0,2,Mortgage,DLD
767,DXB-101368,2026-07-20,Bur Dubai,APT,3 BR,200.9,"AED 1,601,978",3.0,0,Mortgage,DLD
863,DXB-101368,2026-07-20,Bur Dubai,APT,3 BR,200.9,"AED 1,601,978",3.0,0,Mortgage,DLD
184,DXB-101382,2024-04-26,Dubai Hills Estate,Apartment,3 BR,106.8,2327210.0,3.0,1,Sale,DLD
395,DXB-101382,2024-04-26,Dubai Hills Estate,Apartment,3 BR,106.8,2327210.0,3.0,1,Sale,DLD
254,DXB-101419,2024-11-07,Downtown Dubai,Hotel Apartment,2 BR,115.5,4044538.0,2.0,3,Mortgage,Developer
582,DXB-101419,2024-11-07,Downtown Dubai,Hotel Apartment,2 BR,115.5,4044538.0,2.0,3,Mortgage,Developer
596,DXB-101432,2023-04-11,Bur Dubai,apartment,1 BR,187.3,1347409.0,1.0,0,Sale,DLD
1105,DXB-101432,2023-04-11,Bur Dubai,apartment,1 BR,187.3,1347409.0,1.0,0,Sale,DLD
1271,DXB-101491,2026-06-07,Jumeirah Village Circle,Townhouse,3 BR,63.3,639344.0,3.0,3,Sale,Broker
1393,DXB-101491,2026-06-07,Jumeirah Village Circle,Townhouse,3 BR,63.3,639344.0,3.0,3,Sale,Broker

In [67]:
suspicious_duplicate_ids = (
    df.groupby("Transaction_ID")
      .filter(lambda x: len(x.drop_duplicates()) > 1)
      .sort_values("Transaction_ID")
)

suspicious_duplicate_ids

,Transaction_ID,Transaction_Date,Area,Property_Type,Property_Sub_Type,Property_Size_SqM,Transaction_Amount_AED,Rooms,Parking_Spaces,Transaction_Type,Source_Channel
1391,DXB-101063,2023-10-24,Al Barsha,Villa,3 BR,191.8,3036627.0,3.0,0,Sale,DLD
1481,DXB-101063,2023-10-24,Al Barsha,Villa,3 BR,191.8,3036627.0,3.0,0,Sale,DLD
876,DXB-101199,2023-07-03,Business Bay,town house,3 BR,133.3,889496.0,3.0,0,Sale,DLD
1293,DXB-101199,2023-07-03,Business Bay,town house,3 BR,133.3,889496.0,3.0,0,Sale,DLD

In [68]:
for transaction_id in suspicious_duplicate_ids["Transaction_ID"].unique():
    print("\nTransaction ID:", transaction_id)
    print(
        df[df["Transaction_ID"] == transaction_id]
        .T
    )

Transaction ID: DXB-101063
                              1391        1481
Transaction_ID          DXB-101063  DXB-101063
Transaction_Date        2023-10-24  2023-10-24
Area                     Al Barsha   Al Barsha
Property_Type                Villa       Villa
Property_Sub_Type             3 BR        3 BR
Property_Size_SqM            191.8       191.8
Transaction_Amount_AED   3036627.0   3036627.0
Rooms                          3.0         3.0
Parking_Spaces                   0           0
Transaction_Type              Sale        Sale
Source_Channel                DLD          DLD

Transaction ID: DXB-101199
                                876           1293
Transaction_ID            DXB-101199    DXB-101199
Transaction_Date          2023-07-03    2023-07-03
Area                    Business Bay  Business Bay
Property_Type             town house    town house
Property_Sub_Type               3 BR          3 BR
Property_Size_SqM              133.3         133.3
Transaction_Amount_AED      889496.0      889496.0
Rooms                            3.0           3.0
Parking_Spaces                     0             0
Transaction_Type               Sale           Sale
Source_Channel                   DLD           DLD

In [69]:
for transaction_id in suspicious_duplicate_ids["Transaction_ID"].unique():
    rows = df[df["Transaction_ID"] == transaction_id]
    print("\n", transaction_id)
    print(rows.nunique())

 DXB-101063
Transaction_ID            1
Transaction_Date          1
Area                      1
Property_Type             1
Property_Sub_Type         1
Property_Size_SqM         1
Transaction_Amount_AED    1
Rooms                     1
Parking_Spaces            1
Transaction_Type          1
Source_Channel            2
dtype: int64

 DXB-101199
Transaction_ID            1
Transaction_Date          1
Area                      1
Property_Type             1
Property_Sub_Type         1
Property_Size_SqM         1
Transaction_Amount_AED    1
Rooms                     1
Parking_Spaces            1
Transaction_Type          2
Source_Channel            1
dtype: int64

In [70]:
for transaction_id in suspicious_duplicate_ids["Transaction_ID"].unique():
    rows = df[df["Transaction_ID"] == transaction_id]
    
    print("\nTransaction ID:", transaction_id)
    
    for column in rows.columns:
        if rows[column].nunique() > 1:
            print(column, ":", rows[column].unique())

Transaction ID: DXB-101063
Source_Channel : <ArrowStringArray>
[' DLD ', 'DLD']
Length: 2, dtype: str

Transaction ID: DXB-101199
Transaction_Type : <ArrowStringArray>
[' Sale ', 'Sale']
Length: 2, dtype: str

In [71]:
for transaction_id in suspicious_duplicate_ids["Transaction_ID"].unique():
    rows = df[df["Transaction_ID"] == transaction_id]

    print("\nTransaction ID:", transaction_id)

    for column in rows.columns:
        if rows[column].nunique() > 1:
            print(column)
            for value in rows[column].unique():
                print(repr(value))

Transaction ID: DXB-101063
Source_Channel
' DLD '
'DLD'

Transaction ID: DXB-101199
Transaction_Type
' Sale '
'Sale'

In [72]:
string_columns = df.select_dtypes(include="string").columns

for column in string_columns:
    whitespace_count = (
        df[column].dropna()
        .astype(str)
        .str.strip()
        .ne(df[column].dropna().astype(str))
        .sum()
    )
    
    if whitespace_count > 0:
        print(column, ":", whitespace_count)

Area : 42
Property_Type : 101
Transaction_Type : 30
Source_Channel : 30

In [73]:
for column in string_columns:
    cleaned = df[column].dropna().astype(str).str.strip().str.lower()
    
    if cleaned.nunique() < df[column].dropna().nunique():
        print(
            column,
            ":",
            df[column].dropna().nunique(),
            "raw unique values →",
            cleaned.nunique(),
            "normalized unique values"
        )

Area : 27 raw unique values → 18 normalized unique values
Property_Type : 15 raw unique values → 7 normalized unique values
Transaction_Type : 4 raw unique values → 2 normalized unique values
Source_Channel : 6 raw unique values → 3 normalized unique values

In [74]:
for column in ["Area", "Property_Type", "Transaction_Type", "Source_Channel"]:
    print("\n", column)
    print(df[column].dropna().unique())

 Area
<ArrowStringArray>
[ 'Jumeirah Village Circle',                 'Jumeirah',
                'Al Barsha',             'Dubai Marina',
             'Business Bay',       'International City',
       'Dubai Hills Estate',                   'Mirdif',
                'Bur Dubai',     'Jumeirah Lake Towers',
                      'JLT',           'Downtown Dubai',
            'Palm Jumeirah',          'Arabian Ranches',
                    'Deira',  'Jumeirah village circle',
      'Dubai Silicon Oasis',          'Downtown Dubai ',
            'Dubai Marina ',             'Dubai-Marina',
                      'JVC',           'downtown dubai',
             'dubai marina',                      'jlt',
 'Jumeirah Village Circle ',                      'jvc',
    'Jumeirah Lake Towers ']
Length: 27, dtype: str

 Property_Type
<ArrowStringArray>
[      'Apartment',           'Villa',       'APARTMENT', 'Hotel Apartment',
       'Townhouse',       'Penthouse',           'villa',      'Apartment ',
       'apartment',             'APT',           'VILLA',       'TOWNHOUSE',
          'Villa ',      'town house',      'Townhouse ']
Length: 15, dtype: str

 Transaction_Type
<ArrowStringArray>
['Sale', 'Mortgage', ' Mortgage ', ' Sale ']
Length: 4, dtype: str

 Source_Channel
<ArrowStringArray>
['Developer', 'Broker', 'DLD', ' Developer ', ' DLD ', ' Broker ']
Length: 6, dtype: str

In [75]:
print("Property_Type:")
print(df["Property_Type"].dropna().unique())

print("\nTransaction_Type:")
print(df["Transaction_Type"].dropna().unique())

Property_Type:
<ArrowStringArray>
[      'Apartment',           'Villa',       'APARTMENT', 'Hotel Apartment',
       'Townhouse',       'Penthouse',           'villa',      'Apartment ',
       'apartment',             'APT',           'VILLA',       'TOWNHOUSE',
          'Villa ',      'town house',      'Townhouse ']
Length: 15, dtype: str

Transaction_Type:
<ArrowStringArray>
['Sale', 'Mortgage', ' Mortgage ', ' Sale ']
Length: 4, dtype: str

In [76]:
df_clean = df.copy()

# Standardize string columns
string_columns = df_clean.select_dtypes(include="string").columns

for column in string_columns:
    df_clean[column] = (
        df_clean[column]
        .str.strip()
        .str.lower()
    )

print(df_clean.head())

  Transaction_ID Transaction_Date                     Area Property_Type  \
0     dxb-101018       2025-09-21  jumeirah village circle     apartment
1     dxb-100222       2023-06-23                 jumeirah         villa
2     dxb-100310       2026-07-08                al barsha     apartment
3     dxb-101268       2023-07-24             dubai marina     apartment
4     dxb-101361       2025-12-05                 jumeirah     apartment

  Property_Sub_Type  Property_Size_SqM Transaction_Amount_AED  Rooms  \
0              2 br              407.9              4480815.0    2.0
1              6 br               71.7              2034323.0    6.0
2            studio              126.7              2012324.0    0.0
3              1 br               36.8              1064931.0    1.0
4              2 br              114.6          aed 2,170,758    2.0

   Parking_Spaces Transaction_Type Source_Channel
0               3             sale      developer
1               3             sale         broker
2               0             sale      developer
3               2         mortgage            dld
4               3             sale      developer

In [77]:
for column in ["Area", "Property_Type", "Transaction_Type", "Source_Channel"]:
    print("\n", column)
    print(df_clean[column].dropna().unique())

 Area
<ArrowStringArray>
['jumeirah village circle',                'jumeirah',
               'al barsha',            'dubai marina',
            'business bay',      'international city',
      'dubai hills estate',                  'mirdif',
               'bur dubai',    'jumeirah lake towers',
                     'jlt',          'downtown dubai',
           'palm jumeirah',         'arabian ranches',
                   'deira',     'dubai silicon oasis',
            'dubai-marina',                     'jvc']
Length: 18, dtype: str

 Property_Type
<ArrowStringArray>
[      'apartment',           'villa', 'hotel apartment',       'townhouse',
       'penthouse',             'apt',      'town house']
Length: 7, dtype: str

 Transaction_Type
<ArrowStringArray>
['sale', 'mortgage']
Length: 2, dtype: str

 Source_Channel
<ArrowStringArray>
['developer', 'broker', 'dld']
Length: 3, dtype: str

In [78]:
df_clean["Property_Type"] = df_clean["Property_Type"].replace({
    "apt": "apartment",
    "town house": "townhouse"
})

df_clean["Area"] = df_clean["Area"].replace({
    "dubai-marina": "dubai marina"
})

print(df_clean["Property_Type"].dropna().unique())
print(df_clean["Area"].dropna().unique())

<ArrowStringArray>
['apartment', 'villa', 'hotel apartment', 'townhouse', 'penthouse']
Length: 5, dtype: str
<ArrowStringArray>
['jumeirah village circle',                'jumeirah',
               'al barsha',            'dubai marina',
            'business bay',      'international city',
      'dubai hills estate',                  'mirdif',
               'bur dubai',    'jumeirah lake towers',
                     'jlt',          'downtown dubai',
           'palm jumeirah',         'arabian ranches',
                   'deira',     'dubai silicon oasis',
                     'jvc']
Length: 17, dtype: str

In [79]:
df_clean.isna().sum()

Transaction_ID             0
Transaction_Date           0
Area                      37
Property_Type              0
Property_Sub_Type          0
Property_Size_SqM         32
Transaction_Amount_AED    22
Rooms                     37
Parking_Spaces             0
Transaction_Type           0
Source_Channel             0
dtype: int64

In [80]:
missing_rows = df_clean[
    df_clean[["Area", "Property_Size_SqM", "Transaction_Amount_AED", "Rooms"]]
    .isna()
    .any(axis=1)
]

missing_rows[[
    "Transaction_ID",
    "Area",
    "Property_Type",
    "Property_Sub_Type",
    "Property_Size_SqM",
    "Transaction_Amount_AED",
    "Rooms"
]]

,Transaction_ID,Area,Property_Type,Property_Sub_Type,Property_Size_SqM,Transaction_Amount_AED,Rooms
22,dxb-100211,NaN,villa,6 br,88.3,1898903.0,6.0
31,dxb-100838,mirdif,apartment,1 br,52.5,NaN,1.0
34,dxb-100935,deira,apartment,3 br,130.7,1531225.0,NaN
37,dxb-100716,dubai hills estate,villa,6 br,113.1,2130218.0,NaN
96,dxb-101212,palm jumeirah,villa,4 br,39.9,747843.0,NaN
...,...,...,...,...,...,...,...
1418,dxb-100355,palm jumeirah,apartment,2 br,NaN,4258555.0,2.0
1443,dxb-100446,jlt,hotel apartment,1 br,NaN,1397515.0,1.0
1453,dxb-100634,mirdif,apartment,2 br,57.1,NaN,2.0
1466,dxb-100779,palm jumeirah,penthouse,2 br,101.4,3826026.0,NaN
1507,dxb-100192,NaN,apartment,3 br,149.3,3538138.0,3.0

In [81]:
missing_rows.isna().sum(axis=1).value_counts().sort_index()

1    120
2      4
Name: count, dtype: int64

In [82]:
missing_rows[missing_rows.isna().sum(axis=1) == 2]

,Transaction_ID,Transaction_Date,Area,Property_Type,Property_Sub_Type,Property_Size_SqM,Transaction_Amount_AED,Rooms,Parking_Spaces,Transaction_Type,Source_Channel
648,dxb-101037,31/08/2026,international city,apartment,3 br,NaN,NaN,3.0,1,sale,developer
1008,dxb-101423,2025-08-21,palm jumeirah,apartment,3 br,NaN,NaN,3.0,3,sale,broker
1131,dxb-100753,19-oct-2024,jumeirah lake towers,apartment,2 br,NaN,1230253.0,NaN,0,sale,dld
1324,dxb-101040,2025-11-11,jlt,apartment,1 br,NaN,NaN,1.0,0,sale,developer

In [83]:
missing_rows[missing_rows.isna().sum(axis=1) == 1].isna().sum()

Transaction_ID             0
Transaction_Date           0
Area                      37
Property_Type              0
Property_Sub_Type          0
Property_Size_SqM         28
Transaction_Amount_AED    19
Rooms                     36
Parking_Spaces             0
Transaction_Type           0
Source_Channel             0
dtype: int64

In [84]:
df_clean[df_clean["Area"].isna()][
    ["Transaction_ID", "Property_Type", "Property_Sub_Type",
     "Property_Size_SqM", "Transaction_Amount_AED",
     "Rooms", "Transaction_Type", "Source_Channel"]
]

,Transaction_ID,Property_Type,Property_Sub_Type,Property_Size_SqM,Transaction_Amount_AED,Rooms,Transaction_Type,Source_Channel
22,dxb-100211,villa,6 br,88.3,1898903.0,6.0,mortgage,dld
112,dxb-100903,apartment,2 br,151.1,4076063.0,2.0,mortgage,dld
149,dxb-100329,apartment,1 br,131.9,1735994.0,1.0,sale,dld
230,dxb-100752,apartment,2 br,127.4,1745617.0,2.0,mortgage,dld
363,dxb-101085,townhouse,4 br,92.2,"aed 1,153,001",4.0,sale,dld
376,dxb-100600,apartment,2 br,133.4,"aed 4,265,192",2.0,sale,dld
385,dxb-100377,apartment,1 br,83.2,1096382.0,1.0,sale,broker
407,dxb-101133,villa,4 br,69.9,1738850.0,4.0,sale,dld
414,dxb-101287,apartment,2 br,268.4,3259846.0,2.0,sale,broker
485,dxb-100081,apartment,3 br,189.2,2264163.0,3.0,mortgage,dld
547,dxb-100617,apartment,1 br,73.1,2616653.0,1.0,mortgage,dld
560,dxb-100855,apartment,3 br,292.9,7793235.0,3.0,sale,broker
584,dxb-100612,hotel apartment,2 br,8000.0,85000000,2.0,sale,dld
612,dxb-100638,townhouse,2 br,169.3,4899082.0,2.0,sale,dld
660,dxb-100571,townhouse,3 br,120.2,1563280.0,3.0,sale,dld
685,dxb-100094,apartment,2 br,52.1,667789.0,2.0,mortgage,dld
745,dxb-100384,apartment,studio,76.1,1847106.0,0.0,sale,developer
769,dxb-101207,apartment,1 br,101.5,1180056.0,1.0,sale,developer
775,dxb-100127,apartment,studio,210.2,2987172.0,0.0,sale,dld
811,dxb-100256,townhouse,3 br,52.0,652952.0,3.0,sale,dld
942,dxb-101445,villa,3 br,84.8,4171707.0,3.0,mortgage,broker
944,dxb-100699,apartment,3 br,76.8,1941676.0,3.0,sale,dld
984,dxb-101014,apartment,2 br,37.2,697099.0,2.0,sale,broker
986,dxb-100577,villa,3 br,145.6,2341519.0,3.0,mortgage,broker
1041,dxb-100952,apartment,3 br,113.4,-1000000,3.0,mortgage,developer
1047,dxb-100206,apartment,1 br,325.3,3577761.0,1.0,sale,dld
1050,dxb-100694,hotel apartment,1 br,66.1,2330250.0,1.0,sale,dld
1144,dxb-100280,apartment,3 br,62.6,"aed 1,361,050",3.0,sale,developer
1151,dxb-100642,apartment,2 br,38.7,478312.0,2.0,sale,broker
1194,dxb-100905,villa,4 br,92.3,2885477.0,4.0,sale,dld
1205,dxb-100604,hotel apartment,studio,91.4,975298.0,0.0,sale,dld
1234,dxb-101428,townhouse,2 br,132.5,4562591.0,2.0,sale,broker
1274,dxb-101478,apartment,studio,102.1,1313240.0,0.0,mortgage,broker
1308,dxb-101144,apartment,2 br,84.4,2075432.0,2.0,mortgage,broker
1359,dxb-101138,apartment,studio,100.8,1127809.0,0.0,sale,broker
1404,dxb-100922,villa,3 br,39.3,891050.0,3.0,sale,dld
1507,dxb-100192,apartment,3 br,149.3,3538138.0,3.0,mortgage,developer

In [85]:
missing_area_ids = df_clean.loc[
    df_clean["Area"].isna(), "Transaction_ID"
]

df_clean[
    df_clean["Transaction_ID"].isin(missing_area_ids)
][["Transaction_ID", "Area"]].sort_values("Transaction_ID")

     Transaction_ID Area
485      dxb-100081  NaN
685      dxb-100094  NaN
775      dxb-100127  NaN
1507     dxb-100192  NaN
1047     dxb-100206  NaN
22       dxb-100211  NaN
811      dxb-100256  NaN
1144     dxb-100280  NaN
149      dxb-100329  NaN
385      dxb-100377  NaN
745      dxb-100384  NaN
660      dxb-100571  NaN
986      dxb-100577  NaN
376      dxb-100600  NaN
1205     dxb-100604  NaN
584      dxb-100612  NaN
547      dxb-100617  NaN
612      dxb-100638  NaN
1151     dxb-100642  NaN
1050     dxb-100694  NaN
944      dxb-100699  NaN
230      dxb-100752  NaN
560      dxb-100855  NaN
112      dxb-100903  NaN
1194     dxb-100905  NaN
1404     dxb-100922  NaN
1041     dxb-100952  NaN
984      dxb-101014  NaN
363      dxb-101085  NaN
407      dxb-101133  NaN
1359     dxb-101138  NaN
1308     dxb-101144  NaN
769      dxb-101207  NaN
414      dxb-101287  NaN
1234     dxb-101428  NaN
942      dxb-101445  NaN
1274     dxb-101478  NaN

In [86]:
df_clean["Area"] = df_clean["Area"].fillna("unknown")

print(df_clean["Area"].isna().sum())

0

In [87]:
missing_size_ids = df_clean.loc[
    df_clean["Property_Size_SqM"].isna(), "Transaction_ID"
]

df_clean[
    df_clean["Transaction_ID"].isin(missing_size_ids)
][["Transaction_ID", "Property_Size_SqM"]].sort_values("Transaction_ID")

     Transaction_ID  Property_Size_SqM
202      dxb-100012                NaN
1227     dxb-100067                NaN
1001     dxb-100168                NaN
1075     dxb-100209                NaN
447      dxb-100259                NaN
859      dxb-100259                NaN
606      dxb-100267                NaN
626      dxb-100332                NaN
1418     dxb-100355                NaN
1443     dxb-100446                NaN
594      dxb-100558                NaN
921      dxb-100656                NaN
971      dxb-100700                NaN
552      dxb-100722                NaN
676      dxb-100742                NaN
1131     dxb-100753                NaN
215      dxb-100791                NaN
434      dxb-100861                NaN
882      dxb-100861                NaN
1201     dxb-100863                NaN
139      dxb-100886                NaN
1102     dxb-101003                NaN
1192     dxb-101022                NaN
648      dxb-101037                NaN
1324     dxb-101040                NaN
1197     dxb-101093                NaN
1392     dxb-101154                NaN
803      dxb-101294                NaN
451      dxb-101351                NaN
1217     dxb-101353                NaN
1008     dxb-101423                NaN
957      dxb-101474                NaN

In [88]:
df_clean.groupby(
    ["Property_Type", "Property_Sub_Type"]
)["Property_Size_SqM"].median()

Property_Type    Property_Sub_Type
apartment        1 br                 110.40
                 2 br                 107.00
                 3 br                 114.10
                 studio               107.35
hotel apartment  1 br                  94.10
                 2 br                 110.50
                 studio               107.60
penthouse        2 br                 106.65
                 3 br                 117.85
                 4 br                 114.80
townhouse        2 br                 113.90
                 3 br                 118.50
                 4 br                  93.10
villa            3 br                 112.25
                 4 br                 126.40
                 5 br                 114.65
                 6 br                 112.45
Name: Property_Size_SqM, dtype: float64

In [89]:
df_clean["Property_Size_SqM"] = (
    df_clean.groupby(
        ["Property_Type", "Property_Sub_Type"]
    )["Property_Size_SqM"]
    .transform(lambda x: x.fillna(x.median()))
)

print(df_clean["Property_Size_SqM"].isna().sum())

0

In [90]:
print(df_clean["Transaction_Amount_AED"].isna().sum())

22

In [91]:
df_clean["Transaction_Amount_AED"].head(20)

0         4480815.0
1         2034323.0
2         2012324.0
3         1064931.0
4     aed 2,170,758
5         3054340.0
6     aed 2,276,293
7         6759447.0
8         3802875.0
9         2584807.0
10        1291138.0
11        1059119.0
12        2795820.0
13         85000000
14        1381612.0
15        3212161.0
16        1200052.0
17        1813218.0
18        2184626.0
19        1925315.0
Name: Transaction_Amount_AED, dtype: str

In [92]:
df_clean["Transaction_Amount_AED"] = (
    df_clean["Transaction_Amount_AED"]
    .astype(str)
    .str.replace("aed", "", case=False, regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

df_clean["Transaction_Amount_AED"] = pd.to_numeric(
    df_clean["Transaction_Amount_AED"],
    errors="coerce"
)

print(df_clean["Transaction_Amount_AED"].dtype)
print("Missing:", df_clean["Transaction_Amount_AED"].isna().sum())

float64
Missing: 22

In [93]:
df_clean.groupby(["Property_Type", "Property_Sub_Type"])["Transaction_Amount_AED"].median()

Property_Type    Property_Sub_Type
apartment        1 br                 1945895.0
                 2 br                 1969191.0
                 3 br                 1941676.0
                 studio               1810345.0
hotel apartment  1 br                 1724882.5
                 2 br                 2330081.5
                 studio               2323734.0
penthouse        2 br                 2467865.5
                 3 br                 3536775.0
                 4 br                 2653692.0
townhouse        2 br                 2165738.5
                 3 br                 1514735.5
                 4 br                 1702318.0
villa            3 br                 2203418.5
                 4 br                 2682465.5
                 5 br                 2318563.0
                 6 br                 2952783.0
Name: Transaction_Amount_AED, dtype: float64

In [94]:
df_clean["Transaction_Amount_AED"]=(
    df_clean.groupby(
        ["Property_Type", "Property_Sub_Type"]
    )["Transaction_Amount_AED"]
    .transform(lambda x: x.fillna(x.median()))
)

print("Misiing:", df_clean ["Transaction_Amount_AED"].isna().sum())

Misiing: 0

In [95]:
print(df_clean["Rooms"].isna().sum())

37

In [96]:
print(df_clean["Rooms"].dtype)
print(df_clean["Rooms"].value_counts(dropna=False).sort_index())

float64
Rooms
0.0    263
1.0    238
2.0    339
3.0    370
4.0    150
5.0     66
6.0     62
NaN     37
Name: count, dtype: int64

In [97]:
df_clean["Rooms"]=(
    df_clean.groupby(
        ["Property_Type", "Property_Sub_Type"]
    )["Rooms"]
    .transform(lambda x: x.fillna(x.mode().iloc[0]))
)
print("Missing:", df_clean["Rooms"].isna().sum())

Missing: 0

In [98]:
print(df_clean["Area"].isna().sum())
print(df_clean["Area"].value_counts(dropna=False).head(20))

0
Area
jumeirah                   118
business bay               117
palm jumeirah              113
al barsha                  111
downtown dubai             106
dubai hills estate         105
mirdif                      97
jumeirah village circle     91
international city          90
dubai marina                88
deira                       88
arabian ranches             85
bur dubai                   84
dubai silicon oasis         81
jumeirah lake towers        74
unknown                     37
jlt                         23
jvc                         17
Name: count, dtype: int64

In [101]:
df_clean["Area"] = df_clean["Area"].replace(
    {"unknown": "Unknown"}
)

print(df_clean["Area"].value_counts().head(20))
print("Unknown areas:", (df_clean["Area"]=="Unknown").sum())

Area
jumeirah                   118
business bay               117
palm jumeirah              113
al barsha                  111
downtown dubai             106
dubai hills estate         105
mirdif                      97
jumeirah village circle     91
international city          90
dubai marina                88
deira                       88
arabian ranches             85
bur dubai                   84
dubai silicon oasis         81
jumeirah lake towers        74
Unknown                     37
jlt                         23
jvc                         17
Name: count, dtype: int64
Unknown areas: 37

In [102]:
print(df_clean["Transaction_Date"].dtype)
print(df_clean["Transaction_Date"].head(10))
print("Missing dates:", df_clean["Transaction_Date"].isna().sum())

str
0    2025-09-21
1    2023-06-23
2    2026-07-08
3    2023-07-24
4    2025-12-05
5    2024-08-03
6    2024-01-05
7    2025-02-19
8    2024-05-21
9    2024-08-07
Name: Transaction_Date, dtype: str
Missing dates: 0

In [105]:
df_clean["Transaction_Date"] = pd.to_datetime(
    df_clean["Transaction_Date"],
    format="%Y-%m-%d",
    errors="coerce"
)

print(df_clean["Transaction_Date"].dtype)
print("Missing dates:", df_clean["Transaction_Date"].isna().sum())

datetime64[us]
Missing dates: 120

In [106]:
raw_dates = df["Transaction_Date"].astype(str)

parsed_dates = pd.to_datetime(
    raw_dates,
    format= "%Y-%m-%d",
    errors= "coerce"
)

print("Invalid date values:")
print(raw_dates[parsed_dates.isna()].value_counts().head(30))

Invalid date values:
Transaction_Date
08-Sep-2024    2
13-Dec-2025    2
26-Jun-2026    1
14/07/2024     1
09-09-2023     1
03/01/2025     1
18/06/2026     1
05-31-2026     1
11-01-2025     1
02-19-2023     1
02-07-2026     1
28/12/2024     1
04-25-2025     1
10/05/2025     1
24/04/2026     1
11-11-2024     1
27/03/2024     1
08-25-2024     1
29-Jan-2023    1
15/03/2023     1
16-Apr-2026    1
06-Apr-2025    1
05-09-2026     1
28-Jul-2024    1
04-03-2023     1
22/05/2024     1
22-Apr-2023    1
29-Jan-2026    1
18/10/2025     1
09-06-2025     1
Name: count, dtype: int64

In [107]:
df_clean["Transaction_Date"] = pd.to_datetime(
    df_clean["Transaction_Date"],
    format = "mixed",
    errors = "coerce"
)
print(df_clean["Transaction_Date"].dtype)
print("Missing dates", df_clean["Transaction_Date"].isna().sum())

datetime64[us]
Missing dates 120

In [111]:
raw_dates = df["Transaction_Date"].astype(str).str.strip()

parsed_dates = pd.Series(pd.NaT, index=df.index, dtype="datetime64[ns]")

formats = [
    "%Y-%m-%d",
    "%d-%b-%Y",
    "%d/%m/%Y",
    "%m-%d-%Y",
    "%d-%m-%Y"
]

for fmt in formats:
    mask = parsed_dates.isna()
    parsed_dates.loc[mask] = pd.to_datetime(
        raw_dates.loc[mask],
        format=fmt,
        errors="coerce"
    )

print("Missing after parsing:", parsed_dates.isna().sum())
print("Remaining invalid values:")
print(raw_dates[parsed_dates.isna()].value_counts().head(30))

Missing after parsing: 0
Remaining invalid values:
Series([], Name: count, dtype: int64)

In [119]:
df_clean["Transaction_Date"] = parsed_dates.to_numpy()

print(df_clean["Transaction_Date"].dtype)
print("Missing dates:", df_clean["Transaction_Date"].isna().sum())

datetime64[ns]
Missing dates: 1525

In [120]:
print("parsed_dates rows:", len(parsed_dates))
print("parsed_dates missing:", parsed_dates.isna().sum())
print("df_clean rows:", len(df_clean))
print("First parsed dates:")
print(parsed_dates.head())

parsed_dates rows: 1525
parsed_dates missing: 1525
df_clean rows: 1525
First parsed dates:
0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
dtype: datetime64[ns]

In [122]:
raw_dates = pd.read_csv(
    "synthetic_dubai_data/Dubai_Real_Estate_Synthetic_Messy.csv"
)["Transaction_Date"].astype(str).str.strip()

print(raw_dates.head(10))

0    2025-09-21
1    2023-06-23
2    2026-07-08
3    2023-07-24
4    2025-12-05
5    2024-08-03
6    2024-01-05
7    2025-02-19
8    2024-05-21
9    2024-08-07
Name: Transaction_Date, dtype: str

In [123]:
parsed_dates = pd.Series(pd.NaT, index=raw_dates.index, dtype="datetime64[ns]")

formats = [
    "%Y-%m-%d",
    "%d-%b-%Y",
    "%d/%m/%Y",
    "%m-%d-%Y",
    "%d-%m-%Y"
]

for fmt in formats:
    mask = parsed_dates.isna()
    parsed_dates.loc[mask] = pd.to_datetime(
        raw_dates.loc[mask],
        format=fmt,
        errors="coerce"
    )

print("Missing after parsing:", parsed_dates.isna().sum())
print("Remaining invalid values:")
print(raw_dates[parsed_dates.isna()].value_counts().head(30))

Missing after parsing: 0
Remaining invalid values:
Series([], Name: count, dtype: int64)

In [124]:
df_clean["Transaction_Date"] = parsed_dates

print(df_clean["Transaction_Date"].dtype)
print("Missing dates:", df_clean["Transaction_Date"].isna().sum())

datetime64[ns]
Missing dates: 0

In [125]:
print(df_clean["Transaction_Amount_AED"].dtype)
print("Missing amounts:", df_clean["Transaction_Amount_AED"].isna().sum())
print(df_clean["Transaction_Amount_AED"].describe())

float64
Missing amounts: 0
count    1.525000e+03
mean     2.977038e+06
std      5.600408e+06
min     -1.000000e+06
25%      1.250873e+06
50%      2.012324e+06
75%      3.254594e+06
max      8.500000e+07
Name: Transaction_Amount_AED, dtype: float64

In [126]:
print("Negative amounts:", (df_clean["Transaction_Amount_AED"] < 0).sum())

print(
    df_clean.loc[
        df_clean["Transaction_Amount_AED"] < 0,
        ["Transaction_ID", "Transaction_Date", "Property_Type", "Property_Sub_Type", "Transaction_Amount_AED"]
    ]
)

Negative amounts: 8
     Transaction_ID Transaction_Date Property_Type Property_Sub_Type  \
68       dxb-100786       2025-11-14     townhouse              2 br
166      dxb-100859       2023-02-24     apartment              1 br
202      dxb-100012       2023-06-06         villa              3 br
292      dxb-101039       2024-04-12     apartment              3 br
314      dxb-100015       2023-04-22     apartment              3 br
1041     dxb-100952       2023-04-23     apartment              3 br
1185     dxb-100633       2024-03-02     apartment            studio
1498     dxb-100047       2023-07-06     apartment              3 br

      Transaction_Amount_AED
68                -1000000.0
166                -500000.0
202               -1000000.0
292               -1000000.0
314                -500000.0
1041              -1000000.0
1185              -1000000.0
1498              -1000000.0

In [127]:
import numpy as np

df_clean.loc[
    df_clean["Transaction_Amount_AED"] < 0,
    "Transaction_Amount_AED"
] = np.nan

print("Invalid negative amounts remaining:",
      (df_clean["Transaction_Amount_AED"] < 0).sum())

print("Missing amounts:",
      df_clean["Transaction_Amount_AED"].isna().sum())

Invalid negative amounts remaining: 0
Missing amounts: 8

In [128]:
print(df_clean["Property_Size_SqM"].dtype)
print("Missing sizes:", df_clean["Property_Size_SqM"].isna().sum())
print(df_clean["Property_Size_SqM"].describe())

float64
Missing sizes: 0
count     1525.000000
mean       358.154197
std       4453.007563
min        -25.000000
25%         75.900000
50%        110.400000
75%        156.400000
max      99999.000000
Name: Property_Size_SqM, dtype: float64

In [129]:
print("Negative sizes:", (df_clean["Property_Size_SqM"] < 0).sum())

print("Very large sizes:", (df_clean["Property_Size_SqM"] > 5000).sum())

print(
    df_clean.loc[
        (df_clean["Property_Size_SqM"] < 0) |
        (df_clean["Property_Size_SqM"] > 5000),
        ["Transaction_ID", "Property_Type", "Property_Sub_Type", "Property_Size_SqM"]
    ]
)

Negative sizes: 6
Very large sizes: 8
     Transaction_ID    Property_Type Property_Sub_Type  Property_Size_SqM
13       dxb-100485        apartment            studio             8000.0
29       dxb-100581        apartment              2 br             8000.0
163      dxb-100831            villa              6 br             8000.0
334      dxb-100017        apartment            studio            99999.0
382      dxb-101129  hotel apartment            studio            99999.0
418      dxb-100101            villa              6 br              -25.0
584      dxb-100612  hotel apartment              2 br             8000.0
636      dxb-101394        townhouse              3 br              -10.0
983      dxb-100775        penthouse              2 br            99999.0
985      dxb-100713  hotel apartment              1 br             8000.0
994      dxb-100927        penthouse              2 br              -25.0
1028     dxb-100220        apartment              2 br              -10.0
1054     dxb-100660        apartment              1 br              -10.0
1509     dxb-100244            villa              5 br              -10.0

In [130]:
df_clean.loc[
    (df_clean["Property_Size_SqM"] < 0) |
    (df_clean["Property_Size_SqM"] > 5000),
    "Property_Size_SqM"
] = np.nan

print("Invalid sizes remaining:",
      (
          (df_clean["Property_Size_SqM"] < 0) |
          (df_clean["Property_Size_SqM"] > 5000)
      ).sum())

print("Missing sizes:",
      df_clean["Property_Size_SqM"].isna().sum())

Invalid sizes remaining: 0
Missing sizes: 14

In [131]:
print(df_clean["Rooms"].dtype)
print("Missing rooms:", df_clean["Rooms"].isna().sum())
print("Invalid rooms:", (df_clean["Rooms"] < 0).sum())

print(
    df_clean["Rooms"]
    .value_counts(dropna=False)
    .sort_index()
)

float64
Missing rooms: 0
Invalid rooms: 0
Rooms
0.0    266
1.0    242
2.0    351
3.0    381
4.0    154
5.0     66
6.0     65
Name: count, dtype: int64

In [132]:
print(df_clean["Parking_Spaces"].dtype)
print("Missing parking spaces:", df_clean["Parking_Spaces"].isna().sum())
print("Invalid parking spaces:", (df_clean["Parking_Spaces"] < 0).sum())

print(
    df_clean["Parking_Spaces"]
    .value_counts(dropna=False)
    .sort_index()
)

int64
Missing parking spaces: 0
Invalid parking spaces: 0
Parking_Spaces
0    368
1    382
2    403
3    372
Name: count, dtype: int64

In [134]:
print(df_clean["Transaction_Type"].dtype)
print("Missing transaction types:", df_clean["Transaction_Type"].isna().sum())

print(
    df_clean["Transaction_Type"]
    .value_counts(dropna=False)
)

str
Missing transaction types: 0
Transaction_Type
sale        1087
mortgage     438
Name: count, dtype: int64

In [135]:
print(df_clean["Source_Channel"].dtype)
print("Missing source channels:", df_clean["Source_Channel"].isna().sum())

print(
    df_clean["Source_Channel"]
    .value_counts(dropna=False)
)

str
Missing source channels: 0
Source_Channel
dld          993
broker       317
developer    215
Name: count, dtype: int64

In [136]:
print(df_clean["Area"].dtype)
print("Missing areas:", df_clean["Area"].isna().sum())

print(
    df_clean["Area"]
    .value_counts(dropna=False)
)

str
Missing areas: 0
Area
jumeirah                   118
business bay               117
palm jumeirah              113
al barsha                  111
downtown dubai             106
dubai hills estate         105
mirdif                      97
jumeirah village circle     91
international city          90
dubai marina                88
deira                       88
arabian ranches             85
bur dubai                   84
dubai silicon oasis         81
jumeirah lake towers        74
Unknown                     37
jlt                         23
jvc                         17
Name: count, dtype: int64

In [137]:
print("Leading/trailing spaces:",
      df_clean["Area"].ne(df_clean["Area"].str.strip()).sum())

print("Uppercase/mixed-case values:")
print(df_clean["Area"][df_clean["Area"] != df_clean["Area"].str.lower()].value_counts())

Leading/trailing spaces: 0
Uppercase/mixed-case values:
Area
Unknown    37
Name: count, dtype: int64

In [138]:
print(df_clean["Property_Type"].dtype)
print("Missing property types:", df_clean["Property_Type"].isna().sum())

print(
    df_clean["Property_Type"]
    .value_counts(dropna=False)
)

str
Missing property types: 0
Property_Type
apartment          836
villa              263
townhouse          187
hotel apartment    156
penthouse           83
Name: count, dtype: int64

In [139]:
print(df_clean["Property_Sub_Type"].dtype)
print("Missing property sub-types:",
      df_clean["Property_Sub_Type"].isna().sum())

print(
    df_clean["Property_Sub_Type"]
    .value_counts(dropna=False)
)

str
Missing property sub-types: 0
Property_Sub_Type
3 br      381
2 br      351
studio    266
1 br      242
4 br      154
5 br       66
6 br       65
Name: count, dtype: int64

In [140]:
print(
    pd.crosstab(
        df_clean["Property_Type"],
        df_clean["Property_Sub_Type"]
    )
)

Property_Sub_Type  1 br  2 br  3 br  4 br  5 br  6 br  studio
Property_Type
apartment           188   215   226     0     0     0     207
hotel apartment      54    43     0     0     0     0      59
penthouse             0    28    22    33     0     0       0
townhouse             0    65    68    54     0     0       0
villa                 0     0    65    67    66    65       0

In [141]:
print("Total Transaction IDs:", df_clean["Transaction_ID"].nunique())
print("Total rows:", len(df_clean))
print("Duplicate Transaction IDs:", df_clean["Transaction_ID"].duplicated().sum())

Total Transaction IDs: 1500
Total rows: 1525
Duplicate Transaction IDs: 25

In [142]:
print(
    df_clean[df_clean["Transaction_ID"].duplicated(keep=False)]
    .sort_values("Transaction_ID")
    [["Transaction_ID", "Transaction_Date", "Area",
      "Property_Type", "Property_Sub_Type",
      "Transaction_Amount_AED"]]
)

     Transaction_ID Transaction_Date                     Area  \
815      dxb-100051       2023-09-22  jumeirah village circle
933      dxb-100051       2023-09-22  jumeirah village circle
346      dxb-100070       2024-11-22            palm jumeirah
530      dxb-100070       2024-11-22            palm jumeirah
447      dxb-100259       2025-06-25            palm jumeirah
859      dxb-100259       2025-06-25            palm jumeirah
1344     dxb-100413       2024-06-05           downtown dubai
1353     dxb-100413       2024-06-05           downtown dubai
631      dxb-100422       2023-10-10       international city
1461     dxb-100422       2023-10-10       international city
820      dxb-100433       2026-04-30       dubai hills estate
988      dxb-100433       2026-04-30       dubai hills estate
108      dxb-100451       2024-10-30             dubai marina
810      dxb-100451       2024-10-30             dubai marina
459      dxb-100607       2024-09-11          arabian ranches
1124     dxb-100607       2024-09-11          arabian ranches
692      dxb-100712       2024-02-28                    deira
987      dxb-100712       2024-02-28                    deira
705      dxb-100741       2025-07-13                      jlt
1496     dxb-100741       2025-07-13                      jlt
434      dxb-100861       2026-06-16       international city
882      dxb-100861       2026-06-16       international city
290      dxb-100888       2023-03-29  jumeirah village circle
976      dxb-100888       2023-03-29  jumeirah village circle
1391     dxb-101063       2023-10-24                al barsha
1481     dxb-101063       2023-10-24                al barsha
904      dxb-101116       2023-10-27             dubai marina
910      dxb-101116       2023-10-27             dubai marina
501      dxb-101128       2025-05-22      dubai silicon oasis
1022     dxb-101128       2025-05-22      dubai silicon oasis
24       dxb-101190       2023-11-25            palm jumeirah
469      dxb-101190       2023-11-25            palm jumeirah
876      dxb-101199       2023-07-03             business bay
1293     dxb-101199       2023-07-03             business bay
339      dxb-101249       2023-11-10       dubai hills estate
496      dxb-101249       2023-11-10       dubai hills estate
3        dxb-101268       2023-07-24             dubai marina
1085     dxb-101268       2023-07-24             dubai marina
94       dxb-101272       2026-03-28                bur dubai
1352     dxb-101272       2026-03-28                bur dubai
767      dxb-101368       2026-07-20                bur dubai
863      dxb-101368       2026-07-20                bur dubai
184      dxb-101382       2024-04-26       dubai hills estate
395      dxb-101382       2024-04-26       dubai hills estate
254      dxb-101419       2024-11-07           downtown dubai
582      dxb-101419       2024-11-07           downtown dubai
596      dxb-101432       2023-04-11                bur dubai
1105     dxb-101432       2023-04-11                bur dubai
1271     dxb-101491       2026-06-07  jumeirah village circle
1393     dxb-101491       2026-06-07  jumeirah village circle

        Property_Type Property_Sub_Type  Transaction_Amount_AED
815         apartment            studio                757963.0
933         apartment            studio                757963.0
346         apartment              2 br               1822311.0
530         apartment              2 br               1822311.0
447             villa              5 br               4581034.0
859             villa              5 br               4581034.0
1344        penthouse              3 br               5844099.0
1353        penthouse              3 br               5844099.0
631         apartment              2 br                322477.0
1461        apartment              2 br                322477.0
820         townhouse              4 br               2211146.0
988         townhouse              4 br               2211146.0
108         penthouse              2 br               3561526.0
810         penthouse              2 br               3561526.0
459         apartment              3 br               2621540.0
1124        apartment              3 br               2621540.0
692         townhouse              3 br                616398.0
987         townhouse              3 br                616398.0
705         apartment              3 br               1488884.0
1496        apartment              3 br               1488884.0
434         townhouse              4 br                520265.0
882         townhouse              4 br                520265.0
290         apartment              1 br               1879585.0
976         apartment              1 br               1879585.0
1391            villa              3 br               3036627.0
1481            villa              3 br               3036627.0
904         apartment              3 br               1915422.0
910         apartment              3 br               1915422.0
501             villa              4 br               4770509.0
1022            villa              4 br               4770509.0
24          apartment              1 br               2507350.0
469         apartment              1 br               2507350.0
876         townhouse              3 br                889496.0
1293        townhouse              3 br                889496.0
339   hotel apartment            studio               1197129.0
496   hotel apartment            studio               1197129.0
3           apartment              1 br               1064931.0
1085        apartment              1 br               1064931.0
94          apartment              1 br               1233926.0
1352        apartment              1 br               1233926.0
767         apartment              3 br               1601978.0
863         apartment              3 br               1601978.0
184         apartment              3 br               2327210.0
395         apartment              3 br               2327210.0
254   hotel apartment              2 br               4044538.0
582   hotel apartment              2 br               4044538.0
596         apartment              1 br               1347409.0
1105        apartment              1 br               1347409.0
1271        townhouse              3 br                639344.0
1393        townhouse              3 br                639344.0

In [143]:
duplicate_ids = df_clean[df_clean["Transaction_ID"].duplicated(keep=False)]

comparison = (
    duplicate_ids
    .groupby("Transaction_ID")
    .agg(
        rows=("Transaction_ID", "size"),
        unique_dates=("Transaction_Date", "nunique"),
        unique_areas=("Area", "nunique"),
        unique_types=("Property_Type", "nunique"),
        unique_subtypes=("Property_Sub_Type", "nunique"),
        unique_amounts=("Transaction_Amount_AED", "nunique")
    )
)

print(comparison)

                rows  unique_dates  unique_areas  unique_types  \
Transaction_ID
dxb-100051         2             1             1             1
dxb-100070         2             1             1             1
dxb-100259         2             1             1             1
dxb-100413         2             1             1             1
dxb-100422         2             1             1             1
dxb-100433         2             1             1             1
dxb-100451         2             1             1             1
dxb-100607         2             1             1             1
dxb-100712         2             1             1             1
dxb-100741         2             1             1             1
dxb-100861         2             1             1             1
dxb-100888         2             1             1             1
dxb-101063         2             1             1             1
dxb-101116         2             1             1             1
dxb-101128         2             1             1             1
dxb-101190         2             1             1             1
dxb-101199         2             1             1             1
dxb-101249         2             1             1             1
dxb-101268         2             1             1             1
dxb-101272         2             1             1             1
dxb-101368         2             1             1             1
dxb-101382         2             1             1             1
dxb-101419         2             1             1             1
dxb-101432         2             1             1             1
dxb-101491         2             1             1             1

                unique_subtypes  unique_amounts
Transaction_ID
dxb-100051                    1               1
dxb-100070                    1               1
dxb-100259                    1               1
dxb-100413                    1               1
dxb-100422                    1               1
dxb-100433                    1               1
dxb-100451                    1               1
dxb-100607                    1               1
dxb-100712                    1               1
dxb-100741                    1               1
dxb-100861                    1               1
dxb-100888                    1               1
dxb-101063                    1               1
dxb-101116                    1               1
dxb-101128                    1               1
dxb-101190                    1               1
dxb-101199                    1               1
dxb-101249                    1               1
dxb-101268                    1               1
dxb-101272                    1               1
dxb-101368                    1               1
dxb-101382                    1               1
dxb-101419                    1               1
dxb-101432                    1               1
dxb-101491                    1               1

In [144]:
print(comparison[
    (comparison["unique_dates"] > 1) |
    (comparison["unique_areas"] > 1) |
    (comparison["unique_types"] > 1) |
    (comparison["unique_subtypes"] > 1) |
    (comparison["unique_amounts"] > 1)
])

Empty DataFrame
Columns: [rows, unique_dates, unique_areas, unique_types, unique_subtypes, unique_amounts]
Index: []

In [145]:
df_clean = df_clean.drop_duplicates(subset="Transaction_ID", keep="first")

print("Rows after removing duplicate Transaction IDs:", len(df_clean))
print("Unique Transaction IDs:", df_clean["Transaction_ID"].nunique())
print("Duplicate Transaction IDs remaining:", df_clean["Transaction_ID"].duplicated().sum())

Rows after removing duplicate Transaction IDs: 1500
Unique Transaction IDs: 1500
Duplicate Transaction IDs remaining: 0

In [146]:
print("Unique Property Types:")
print(df_clean["Property_Type"].unique())

print("\nUnique Transaction Types:")
print(df_clean["Transaction_Type"].unique())

print("\nUnique Source Channels:")
print(df_clean["Source_Channel"].unique())

Unique Property Types:
<ArrowStringArray>
['apartment', 'villa', 'hotel apartment', 'townhouse', 'penthouse']
Length: 5, dtype: str

Unique Transaction Types:
<ArrowStringArray>
['sale', 'mortgage']
Length: 2, dtype: str

Unique Source Channels:
<ArrowStringArray>
['developer', 'broker', 'dld']
Length: 3, dtype: str

In [147]:
print("Invalid Transaction IDs:")

invalid_ids = df_clean[
    ~df_clean["Transaction_ID"].str.match(r"^dxb-\d{6}$", na=False)
]

print(invalid_ids[["Transaction_ID"]])
print("Count:", len(invalid_ids))

Invalid Transaction IDs:
Empty DataFrame
Columns: [Transaction_ID]
Index: []
Count: 0

In [148]:
print("Minimum transaction date:", df_clean["Transaction_Date"].min())
print("Maximum transaction date:", df_clean["Transaction_Date"].max())

Minimum transaction date: 2023-01-01 00:00:00
Maximum transaction date: 2026-08-31 00:00:00

In [149]:
print("Future dates:", (df_clean["Transaction_Date"] > pd.Timestamp.today()).sum())

Future dates: 0

In [150]:
print("Zero amounts:", (df_clean["Transaction_Amount_AED"] == 0).sum())
print("Negative amounts:", (df_clean["Transaction_Amount_AED"] < 0).sum())
print("Missing amounts:", df_clean["Transaction_Amount_AED"].isna().sum())

Zero amounts: 2
Negative amounts: 0
Missing amounts: 8

In [151]:
print(
    df_clean.loc[
        (df_clean["Transaction_Amount_AED"] <= 0) |
        (df_clean["Transaction_Amount_AED"].isna()),
        ["Transaction_ID", "Transaction_Date", "Property_Type",
         "Property_Sub_Type", "Transaction_Amount_AED"]
    ]
)

     Transaction_ID Transaction_Date Property_Type Property_Sub_Type  \
68       dxb-100786       2025-11-14     townhouse              2 br
166      dxb-100859       2023-02-24     apartment              1 br
202      dxb-100012       2023-06-06         villa              3 br
292      dxb-101039       2024-04-12     apartment              3 br
314      dxb-100015       2023-04-22     apartment              3 br
322      dxb-100515       2024-09-20     apartment              3 br
777      dxb-101425       2025-10-12     apartment            studio
1041     dxb-100952       2023-04-23     apartment              3 br
1185     dxb-100633       2024-03-02     apartment            studio
1498     dxb-100047       2023-07-06     apartment              3 br

      Transaction_Amount_AED
68                       NaN
166                      NaN
202                      NaN
292                      NaN
314                      NaN
322                      0.0
777                      0.0
1041                     NaN
1185                     NaN
1498                     NaN

In [152]:
print(
    df_clean.loc[
        (df_clean["Transaction_Amount_AED"] <= 0) |
        (df_clean["Transaction_Amount_AED"].isna()),
        "Transaction_ID"
    ].duplicated().sum()
)

0

In [153]:
problem_ids = df_clean.loc[
    (df_clean["Transaction_Amount_AED"] <= 0) |
    (df_clean["Transaction_Amount_AED"].isna()),
    "Transaction_ID"
]

print(
    df.loc[
        df["Transaction_ID"].isin(problem_ids),
        ["Transaction_ID", "Transaction_Amount_AED"]
    ]
)

Empty DataFrame
Columns: [Transaction_ID, Transaction_Amount_AED]
Index: []

In [154]:
print("Problematic amount records:", len(problem_ids))
print("Percentage of dataset:", round(len(problem_ids) / len(df_clean) * 100, 2), "%")

Problematic amount records: 10
Percentage of dataset: 0.67 %

In [155]:
df_clean = df_clean[
    df_clean["Transaction_Amount_AED"].notna() &
    (df_clean["Transaction_Amount_AED"] > 0)
].copy()

print("Rows after amount cleaning:", len(df_clean))
print("Missing amounts:", df_clean["Transaction_Amount_AED"].isna().sum())
print("Zero amounts:", (df_clean["Transaction_Amount_AED"] == 0).sum())
print("Negative amounts:", (df_clean["Transaction_Amount_AED"] < 0).sum())

Rows after amount cleaning: 1490
Missing amounts: 0
Zero amounts: 0
Negative amounts: 0

In [156]:
print("Missing property sizes:",
      df_clean["Property_Size_SqM"].isna().sum())

print(
    df_clean.loc[
        df_clean["Property_Size_SqM"].isna(),
        ["Transaction_ID", "Property_Type", "Property_Sub_Type",
         "Transaction_Amount_AED", "Rooms"]
    ]
)

Missing property sizes: 14
     Transaction_ID    Property_Type Property_Sub_Type  \
13       dxb-100485        apartment            studio
29       dxb-100581        apartment              2 br
163      dxb-100831            villa              6 br
334      dxb-100017        apartment            studio
382      dxb-101129  hotel apartment            studio
418      dxb-100101            villa              6 br
584      dxb-100612  hotel apartment              2 br
636      dxb-101394        townhouse              3 br
983      dxb-100775        penthouse              2 br
985      dxb-100713  hotel apartment              1 br
994      dxb-100927        penthouse              2 br
1028     dxb-100220        apartment              2 br
1054     dxb-100660        apartment              1 br
1509     dxb-100244            villa              5 br

      Transaction_Amount_AED  Rooms
13                85000000.0    0.0
29                85000000.0    2.0
163               85000000.0    6.0
334                 966547.0    0.0
382                2987984.0    0.0
418                6417414.0    6.0
584               85000000.0    2.0
636                3956062.0    3.0
983                1737798.0    2.0
985               60000000.0    1.0
994                 934945.0    2.0
1028               1958325.0    2.0
1054               1822939.0    1.0
1509               3611911.0    5.0

In [157]:
print(
    df_clean.groupby("Property_Sub_Type")["Property_Size_SqM"]
    .agg(["count", "median", "mean"])
)

                   count   median        mean
Property_Sub_Type
1 br                 234  105.200  124.807265
2 br                 341  107.000  138.610850
3 br                 364  114.800  143.051923
4 br                 151  110.700  125.082119
5 br                  64  115.825  129.555469
6 br                  63  112.450  146.219841
studio               259  107.350  145.172008

In [158]:
df_clean["Property_Size_SqM"] = df_clean["Property_Size_SqM"].fillna(
    df_clean.groupby("Property_Sub_Type")["Property_Size_SqM"].transform("median")
)

print("Missing property sizes after cleaning:",
      df_clean["Property_Size_SqM"].isna().sum())

Missing property sizes after cleaning: 0

In [159]:
print("Missing rooms:", df_clean["Rooms"].isna().sum())

print(
    df_clean.loc[
        df_clean["Rooms"].isna(),
        ["Transaction_ID", "Property_Type", "Property_Sub_Type", "Property_Size_SqM"]
    ]
)

Missing rooms: 0
Empty DataFrame
Columns: [Transaction_ID, Property_Type, Property_Sub_Type, Property_Size_SqM]
Index: []

In [160]:
print("Missing parking spaces:",
      df_clean["Parking_Spaces"].isna().sum())

print("Negative parking spaces:",
      (df_clean["Parking_Spaces"] < 0).sum())

print("Unique parking spaces:")
print(df_clean["Parking_Spaces"].value_counts(dropna=False).sort_index())

Missing parking spaces: 0
Negative parking spaces: 0
Unique parking spaces:
Parking_Spaces
0    353
1    375
2    398
3    364
Name: count, dtype: int64

In [161]:
print("Unknown areas:",
      (df_clean["Area"] == "Unknown").sum())

print(
    df_clean.loc[
        df_clean["Area"] == "Unknown",
        ["Transaction_ID", "Property_Type", "Property_Sub_Type",
         "Property_Size_SqM", "Transaction_Amount_AED"]
    ]
)

Unknown areas: 36
     Transaction_ID    Property_Type Property_Sub_Type  Property_Size_SqM  \
22       dxb-100211            villa              6 br               88.3
112      dxb-100903        apartment              2 br              151.1
149      dxb-100329        apartment              1 br              131.9
230      dxb-100752        apartment              2 br              127.4
363      dxb-101085        townhouse              4 br               92.2
376      dxb-100600        apartment              2 br              133.4
385      dxb-100377        apartment              1 br               83.2
407      dxb-101133            villa              4 br               69.9
414      dxb-101287        apartment              2 br              268.4
485      dxb-100081        apartment              3 br              189.2
547      dxb-100617        apartment              1 br               73.1
560      dxb-100855        apartment              3 br              292.9
584      dxb-100612  hotel apartment              2 br              107.0
612      dxb-100638        townhouse              2 br              169.3
660      dxb-100571        townhouse              3 br              120.2
685      dxb-100094        apartment              2 br               52.1
745      dxb-100384        apartment            studio               76.1
769      dxb-101207        apartment              1 br              101.5
775      dxb-100127        apartment            studio              210.2
811      dxb-100256        townhouse              3 br               52.0
942      dxb-101445            villa              3 br               84.8
944      dxb-100699        apartment              3 br               76.8
984      dxb-101014        apartment              2 br               37.2
986      dxb-100577            villa              3 br              145.6
1047     dxb-100206        apartment              1 br              325.3
1050     dxb-100694  hotel apartment              1 br               66.1
1144     dxb-100280        apartment              3 br               62.6
1151     dxb-100642        apartment              2 br               38.7
1194     dxb-100905            villa              4 br               92.3
1205     dxb-100604  hotel apartment            studio               91.4
1234     dxb-101428        townhouse              2 br              132.5
1274     dxb-101478        apartment            studio              102.1
1308     dxb-101144        apartment              2 br               84.4
1359     dxb-101138        apartment            studio              100.8
1404     dxb-100922            villa              3 br               39.3
1507     dxb-100192        apartment              3 br              149.3

      Transaction_Amount_AED
22                 1898903.0
112                4076063.0
149                1735994.0
230                1745617.0
363                1153001.0
376                4265192.0
385                1096382.0
407                1738850.0
414                3259846.0
485                2264163.0
547                2616653.0
560                7793235.0
584               85000000.0
612                4899082.0
660                1563280.0
685                 667789.0
745                1847106.0
769                1180056.0
775                2987172.0
811                 652952.0
942                4171707.0
944                1941676.0
984                 697099.0
986                2341519.0
1047               3577761.0
1050               2330250.0
1144               1361050.0
1151                478312.0
1194               2885477.0
1205                975298.0
1234               4562591.0
1274               1313240.0
1308               2075432.0
1359               1127809.0
1404                891050.0
1507               3538138.0

In [162]:
print("Missing Area:", df_clean["Area"].isna().sum())
print("Unknown Area:", (df_clean["Area"] == "Unknown").sum())

print("\nUnique Transaction Types:")
print(df_clean["Transaction_Type"].value_counts(dropna=False))

print("\nUnique Source Channels:")
print(df_clean["Source_Channel"].value_counts(dropna=False))

Missing Area: 0
Unknown Area: 36

Unique Transaction Types:
Transaction_Type
sale        1067
mortgage     423
Name: count, dtype: int64

Unique Source Channels:
Source_Channel
dld          965
broker       314
developer    211
Name: count, dtype: int64

In [163]:
print("Remaining missing values:")
print(df_clean.isna().sum())

Remaining missing values:
Transaction_ID               0
Transaction_Date             0
Area                         0
Property_Type                0
Property_Sub_Type            0
Property_Size_SqM            0
Transaction_Amount_AED       0
Rooms                        0
Parking_Spaces               0
Transaction_Type             0
Source_Channel               0
Transaction               1490
dtype: int64

In [164]:
print("Final row count:", len(df_clean))
print("Unique Transaction IDs:", df_clean["Transaction_ID"].nunique())
print("Duplicate Transaction IDs:", df_clean["Transaction_ID"].duplicated().sum())

Final row count: 1490
Unique Transaction IDs: 1490
Duplicate Transaction IDs: 0

In [165]:
print(df_clean.dtypes)

Transaction_ID                       str
Transaction_Date          datetime64[ns]
Area                                 str
Property_Type                        str
Property_Sub_Type                    str
Property_Size_SqM                float64
Transaction_Amount_AED           float64
Rooms                            float64
Parking_Spaces                     int64
Transaction_Type                     str
Source_Channel                       str
Transaction               datetime64[ns]
dtype: object

In [166]:
print(df_clean.columns.tolist())

['Transaction_ID', 'Transaction_Date', 'Area', 'Property_Type', 'Property_Sub_Type', 'Property_Size_SqM', 'Transaction_Amount_AED', 'Rooms', 'Parking_Spaces', 'Transaction_Type', 'Source_Channel', 'Transaction']

In [168]:
print(df_clean[["Transaction_ID", "Transaction"]].head(10))

  Transaction_ID Transaction
0     dxb-101018         NaT
1     dxb-100222         NaT
2     dxb-100310         NaT
3     dxb-101268         NaT
4     dxb-101361         NaT
5     dxb-100307         NaT
6     dxb-100292         NaT
7     dxb-101103         NaT
8     dxb-100491         NaT
9     dxb-100509         NaT

In [169]:
df_clean = df_clean.drop(columns=["Transaction"])

print("Columns after removing extra column:")
print(df_clean.columns.tolist())

Columns after removing extra column:
['Transaction_ID', 'Transaction_Date', 'Area', 'Property_Type', 'Property_Sub_Type', 'Property_Size_SqM', 'Transaction_Amount_AED', 'Rooms', 'Parking_Spaces', 'Transaction_Type', 'Source_Channel']

In [170]:
print("Number of columns:", len(df_clean.columns))
print("Number of rows:", len(df_clean))
print(df_clean.columns.tolist())

Number of columns: 11
Number of rows: 1490
['Transaction_ID', 'Transaction_Date', 'Area', 'Property_Type', 'Property_Sub_Type', 'Property_Size_SqM', 'Transaction_Amount_AED', 'Rooms', 'Parking_Spaces', 'Transaction_Type', 'Source_Channel']

In [172]:
import os

os.makedirs("data/official", exist_ok=True)

print("Folder ready.")

Folder ready.

In [173]:
df_clean.to_csv(
    "data/official/Dubai_Real_Estate_Cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [174]:
df_check = pd.read_csv("data/official/Dubai_Real_Estate_Cleaned.csv")

print(df_check.shape)
print(df_check.isna().sum())
print(df_check.head())

(1490, 11)
Transaction_ID            0
Transaction_Date          0
Area                      0
Property_Type             0
Property_Sub_Type         0
Property_Size_SqM         0
Transaction_Amount_AED    0
Rooms                     0
Parking_Spaces            0
Transaction_Type          0
Source_Channel            0
dtype: int64
  Transaction_ID Transaction_Date                     Area Property_Type  \
0     dxb-101018       2025-09-21  jumeirah village circle     apartment
1     dxb-100222       2023-06-23                 jumeirah         villa
2     dxb-100310       2026-07-08                al barsha     apartment
3     dxb-101268       2023-07-24             dubai marina     apartment
4     dxb-101361       2025-12-05                 jumeirah     apartment

  Property_Sub_Type  Property_Size_SqM  Transaction_Amount_AED  Rooms  \
0              2 br              407.9               4480815.0    2.0
1              6 br               71.7               2034323.0    6.0
2            studio              126.7               2012324.0    0.0
3              1 br               36.8               1064931.0    1.0
4              2 br              114.6               2170758.0    2.0

   Parking_Spaces Transaction_Type Source_Channel
0               3             sale      developer
1               3             sale         broker
2               0             sale      developer
3               2         mortgage            dld
4               3             sale      developer

In [176]:
import pandas as pd

# Load the cleaned CSV
df_clean = pd.read_csv("data/official/Dubai_Real_Estate_Cleaned.csv")

# Correct the two property sizes that were fixed in PostgreSQL
df_clean.loc[
    df_clean["Transaction_ID"] == "dxb-100882",
    "Property_Size_SqM"
] = 105.20

df_clean.loc[
    df_clean["Transaction_ID"] == "dxb-101001",
    "Property_Size_SqM"
] = 107.35

# Save the corrected CSV
df_clean.to_csv(
    "data/official/Dubai_Real_Estate_Cleaned.csv",
    index=False
)

print("CSV updated successfully.")

CSV updated successfully.

In [177]:
df_check = pd.read_csv("data/official/Dubai_Real_Estate_Cleaned.csv")

print(
    df_check.loc[
        df_check["Transaction_ID"].isin(["dxb-100882", "dxb-101001"]),
        ["Transaction_ID", "Property_Size_SqM"]
    ]
)

     Transaction_ID  Property_Size_SqM
1375     dxb-100882             105.20
1396     dxb-101001             107.35